---
title: "MOFA and CLL: downsampling analysis "
author: "Ricard Argelaguet"
date: "`r Sys.Date()`"
output:
  BiocStyle::html_document:
    toc: true
---

```{r}
# devtools::load_all("/Users/ricard/mofa/MOFAtools")
devtools::load_all("/homes/ricard/mofa/MOFAtools")
library(data.table)
library(purrr)
library(ggplot2)
source("/homes/ricard/MOFA_CLL/downsampling/predictSurvival.R")
```

```{r}
theme_fn <- function() {
  theme(
    axis.title= element_text(size=rel(1.7)),
    axis.text = element_text(color="black", size=rel(1.3)),
    legend.position = "top",
    legend.direction='vertical',
    legend.title = element_blank(),
    legend.text = element_text(size=rel(1.3))
    )
}
```

```{r}
# in.folder <- "/Users/ricard/data/downsample/results2/mRNA"
in.folder <- "/hps/nobackup/stegle/users/ricard/downsample/results"

nsamples_downsampled <- seq(0,50,5)
ntrials <- 25
```


```{r}

# Load reactome data
# reactome <- readRDS("/Users/ricard/data/reactome/v59/homo_sapiens/out/human_reactome.rds")
# tmp <- read.table("/Users/ricard/data/reactome/v59/homo_sapiens/AllPathways.txt", header=F, quote="", sep="\t", stringsAsFactors=F)[,c(1,2)]
reactome <- readRDS("/hps/nobackup/stegle/users/ricard/reactome/v59/homo_sapiens/out/human_reactome.rds")
tmp <- read.table("/hps/nobackup/stegle/users/ricard/reactome/v59/homo_sapiens/AllPathways.txt", header=F, quote="", sep="\t", stringsAsFactors=F)[,c(1,2)]
reactome_meta <- tmp[,2]; names(reactome_meta) <- tmp[,1]
rownames(reactome) <- stringr::str_replace_all(rownames(reactome), reactome_meta)

# Initialise data tables to store results
tmp_ngenesets <- expand.grid(nsamples_downsampled,1:ntrials) %>% as.data.table %>% setnames(c("nsamples_downsampled","trial")) %>%
  .[,c("completeD_completeM","completeD_incompleteM","incompleteD_completeM","incompleteD_incompleteM","imputed_complete","imputed_incomplete"):=0]
tmp_nfactors <- expand.grid(nsamples_downsampled,1:ntrials) %>% as.data.table %>% setnames(c("nsamples_downsampled","trial")) %>%
  .[,c("completeD_completeM","completeD_incompleteM","incompleteD_completeM","incompleteD_incompleteM","imputed_complete","imputed_incomplete"):=0]
tmp_survival <- expand.grid(nsamples_downsampled,1:ntrials) %>% as.data.table %>% setnames(c("nsamples_downsampled","trial")) %>%
  .[,c("completeD_completeM","completeD_incompleteM","incompleteD_completeM","incompleteD_incompleteM","imputed_complete","imputed_incomplete"):=0]

for (n in nsamples_downsampled) {
  print(n)
  for (i in 1:ntrials) {
    
    # Define model files
    # incompleteD_incompleteM_file <- paste0(in.folder,"/incompleteD_incompleteM_",n,"_",i,".hdf5")
    # incompleteD_completeM_file <- paste0(in.folder,"/incompleteD_completeM_",n,"_",i,".hdf5")
    completeD_incompleteM_file <- paste0(in.folder,"/completeD_incompleteM_",n,"_",i,".hdf5")
    completeD_completeM_file <- paste0(in.folder,"/completeD_completeM_",n,"_",i,".hdf5")
    # imputed_incomplete_file <- paste0(in.folder,"/incomplete_imputed_",n,"_",i,".hdf5")
    imputed_complete_file <- paste0(in.folder,"/complete_imputed_",n,"_",i,".hdf5")
    
    # if (all(file.exists(incompleteD_incompleteM_file,incompleteD_completeM_file,completeD_incompleteM_file,completeD_completeM_file,imputed_incomplete_file,imputed_complete_file))) {
    
    # Load Models
    # incompleteD_incompleteM_model <- loadModel(incompleteD_incompleteM_file, sortFactors=F)
    # incompleteD_completeM_model <- loadModel(incompleteD_completeM_file, sortFactors=F)
    completeD_incompleteM_model <- loadModel(completeD_incompleteM_file, sortFactors=F)
    completeD_completeM_model <- loadModel(completeD_completeM_file, sortFactors=F)
    # imputed_incomplete_model <- loadModel(imputed_incomplete_file, sortFactors=F)
    imputed_complete_model <- loadModel(imputed_complete_file, sortFactors=F)
    
    # Survival prediction
    # tmp_survival[nsamples_downsampled==n & trial==i, incompleteD_incompleteM:=predictSurvival(incompleteD_incompleteM_model)[1] ]
    # tmp_survival[nsamples_downsampled==n & trial==i, incompleteD_completeM:=predictSurvival(incompleteD_completeM_model)[1] ]
    tmp_survival[nsamples_downsampled==n & trial==i, completeD_incompleteM:=predictSurvival(completeD_incompleteM_model)[1] ]
    tmp_survival[nsamples_downsampled==n & trial==i, completeD_completeM:=predictSurvival(completeD_completeM_model)[1] ]
    # tmp_survival[nsamples_downsampled==n & trial==i, imputed_incomplete:=predictSurvival(imputed_incomplete_model)[1] ]
    tmp_survival[nsamples_downsampled==n & trial==i, imputed_complete:=predictSurvival(imputed_complete_model)[1] ]
    
    # Number of factors
    # tmp_nfactors[nsamples_downsampled==n & trial==i, incompleteD_incompleteM:=getDimensions(incompleteD_incompleteM_model)[["K"]]]
    # tmp_nfactors[nsamples_downsampled==n & trial==i, incompleteD_completeM:=getDimensions(incompleteD_completeM_model)[["K"]]]
    tmp_nfactors[nsamples_downsampled==n & trial==i, completeD_incompleteM:=getDimensions(completeD_incompleteM_model)[["K"]]]
    tmp_nfactors[nsamples_downsampled==n & trial==i, completeD_completeM:=getDimensions(completeD_completeM_model)[["K"]]]
    # tmp_nfactors[nsamples_downsampled==n & trial==i, imputed_incomplete:=getDimensions(imputed_incomplete_model)[["K"]]]
    tmp_nfactors[nsamples_downsampled==n & trial==i, imputed_complete:=getDimensions(imputed_complete_model)[["K"]]]
    
    # Number of enriched pathways in the mRNA view
    # npathways_incompleteD_incompleteM <- FeatureSetEnrichmentAnalysis(incompleteD_incompleteM_model, "mRNA", reactome, local.statistic = "loading", 
    #                                      transformation = "abs.value", global.statistic = "mean.diff", statistical.test = "parametric", min.size=15)$pval.adj
    # npathways_incompleteD_completeM <- FeatureSetEnrichmentAnalysis(incompleteD_completeM_model, "mRNA", reactome, local.statistic = "loading", 
    #                                      transformation = "abs.value", global.statistic = "mean.diff", statistical.test = "parametric", min.size=15)$pval.adj
    npathways_completeD_incompleteM <- FeatureSetEnrichmentAnalysis(completeD_incompleteM_model, "mRNA", reactome, local.statistic = "loading",
                                         transformation = "abs.value", global.statistic = "mean.diff", statistical.test = "parametric", min.size=15)$pval.adj
    npathways_completeD_completeM <- FeatureSetEnrichmentAnalysis(completeD_completeM_model, "mRNA", reactome, local.statistic = "loading",
                                         transformation = "abs.value", global.statistic = "mean.diff", statistical.test = "parametric", min.size=15)$pval.adj
    # npathways_imputed_incomplete <- FeatureSetEnrichmentAnalysis(imputed_incomplete_model, "mRNA", reactome, local.statistic = "loading", 
    #                                      transformation = "abs.value", global.statistic = "mean.diff", statistical.test = "parametric", min.size=15)$pval.adj
    npathways_imputed_complete <- FeatureSetEnrichmentAnalysis(imputed_complete_model, "mRNA", reactome, local.statistic = "loading",
                                         transformation = "abs.value", global.statistic = "mean.diff", statistical.test = "parametric", min.size=15)$pval.adj
    
    # tmp_ngenesets[nsamples_downsampled==n & trial==i, incompleteD_incompleteM:=sum(npathways_incompleteD_incompleteM<0.1, na.rm=T)]
    # tmp_ngenesets[nsamples_downsampled==n & trial==i, incompleteD_completeM:=sum(npathways_incompleteD_completeM<0.1, na.rm=T)]
    tmp_ngenesets[nsamples_downsampled==n & trial==i, completeD_incompleteM:=sum(npathways_completeD_incompleteM<0.1, na.rm=T)]
    tmp_ngenesets[nsamples_downsampled==n & trial==i, completeD_completeM:=sum(npathways_completeD_completeM<0.1, na.rm=T)]
    # tmp_ngenesets[nsamples_downsampled==n & trial==i, imputed_incomplete:=sum(npathways_imputed_incomplete<0.1, na.rm=T)]
    tmp_ngenesets[nsamples_downsampled==n & trial==i, imputed_complete:=sum(npathways_imputed_complete<0.1, na.rm=T)]
    
    # } else { print(paste0("Error with n=",n," and trial=",i)) }
    
  }
}
```

<!-- Parse results -->
```{r}
tmp2_ngenesets <- melt(tmp_ngenesets,  measure.vars=c("incompleteD_incompleteM","incompleteD_completeM","completeD_incompleteM","completeD_completeM","imputed_incomplete","imputed_complete"), variable.name="type", value.name="ngenesets") %>%
  .[,c("nsamples_downsampled","trial"):=list(as.factor(nsamples_downsampled),as.factor(trial))]# %>% .[,nsamples_downsampled:=as.numeric(nsamples_downsampled)]
tmp2_nfactors <- melt(tmp_nfactors,  measure.vars=c("incompleteD_incompleteM","incompleteD_completeM","completeD_incompleteM","completeD_completeM","imputed_incomplete","imputed_complete"), variable.name="type", value.name="nfactors") %>%
  .[,c("nsamples_downsampled","trial"):=list(as.factor(nsamples_downsampled),as.factor(trial))]# %>% .[,nsamples_downsampled:=as.numeric(nsamples_downsampled)]
tmp2_survival <- melt(tmp_survival,  measure.vars=c("incompleteD_incompleteM","incompleteD_completeM","completeD_incompleteM","completeD_completeM","imputed_incomplete","imputed_complete"), variable.name="type", value.name="survival") %>%
  .[,c("nsamples_downsampled","trial"):=list(as.factor(nsamples_downsampled),as.factor(trial))]# %>% .[,nsamples_downsampled:=as.numeric(nsamples_downsampled)]

```



<!-- Plot results -->
```{r}

# Number of enriched gene sets
pdf("/homes/ricard/MOFA_CLL/downsampling/out/ngenesets.pdf", width = 7.5, height = 5.5)
p <- ggplot(tmp2_ngenesets[ngenesets>0], aes(x=nsamples_downsampled, y=ngenesets, group=type, color=type)) +
  stat_summary(fun.y="mean", geom="line", size=1) +
  stat_summary(fun.data="mean_se", geom="errorbar", width=0.01, alpha=0.6) +
  theme_bw() + theme_fn() +
  labs(x="Downsampling number", y="Number of enriched gene sets")
  # scale_color_discrete(labels=c(
  #   "Incomplete Data + Incomplete Model",
  #   "Incomplete Data + Complete Model",
  #   "Complete Data + Incomplete Model",
  #   "Complete Data + Complete Model",
  #   "Imputed Incomplete Data",
  #   "Imputed Complete Data"))
print(p)
dev.off()

# Number of factors
pdf("/homes/ricard/MOFA_CLL/downsampling/out/nfactors.pdf", width = 7.5, height = 5.5)
p <- ggplot(tmp2_nfactors[nfactors>0], aes(x=nsamples_downsampled, y=nfactors, group=type, color=type)) +
  stat_summary(fun.y="mean", geom="line", size=1) +
  stat_summary(fun.data="mean_se", geom="errorbar", width=0.01, alpha=0.6) +
  theme_bw() + theme_fn() +
  labs(x="Downsampling number", y="Number of factors")
  # scale_color_discrete(labels=c(
  #   "Incomplete Data + Incomplete Model",
  #   "Incomplete Data + Complete Model",
  #   "Complete Data + Incomplete Model",
  #   "Complete Data + Complete Model",
  #   "Imputed Incomplete Data",
  #   "Imputed Complete Data"))
  # scale_color_discrete(labels=c(
  #   "Incomplete Data + Incomplete Model",
  #   "Incomplete Data + Complete Model",
  #   "Imputed Incomplete Data"))
  # scale_color_discrete(labels=c(
  #   "Complete Data + Incomplete Model",
  #   "Complete Data + Complete Model",
  #   "Imputed Complete Data"))
print(p)
dev.off()

# Survival prediction
pdf("/homes/ricard/MOFA_CLL/downsampling/out/survival.pdf", width = 7.5, height = 5.5)
p <- ggplot(tmp2_survival[survival>0], aes(x=nsamples_downsampled, y=survival, group=type, color=type)) +
  stat_summary(fun.y="mean", geom="line", size=1) +
  stat_summary(fun.data="mean_se", geom="errorbar", width=0.01, alpha=0.6) +
  theme_bw() + theme_fn() +
  labs(x="Downsampling number", y="Harrell's C-index")
  # scale_color_discrete(labels=c(
  #   "Incomplete Data + Incomplete Model",
  #   "Incomplete Data + Complete Model",
  #   "Complete Data + Incomplete Model",
  #   "Complete Data + Complete Model",
  #   "Imputed Incomplete Data",
  #   "Imputed Complete Data"))
  # scale_color_discrete(labels=c(
  #   "Incomplete Data + Incomplete Model",
  #   "Incomplete Data + Complete Model",
  #   "Imputed Incomplete Data"))
print(p)
dev.off()
```


<!-- <!-- Imputation of drug response --> -->
<!-- ```{r} -->

<!-- # Load ground truth data -->
<!-- # Y <- read.table("/Users/ricard/data/CLL/views/minView=2/viab.txt", header=T) %>% as.matrix -->
<!-- Y <- read.table("/hps/nobackup/stegle/users/ricard/CLL/views/minView=2/viab.txt", header=T) %>% as.matrix -->
<!-- Y <- apply(Y, 2, function(x) x - mean(x,na.rm=T)) %>% t -->

<!-- tmp <- expand.grid(nsamples_downsampled,1:ntrials) %>% as.data.table %>% setnames(c("nsamples_downsampled","trial")) -->
<!-- tmp[,c("complete_mse","incomplete_mse"):=0] -->

<!-- for (n in nsamples_downsampled) { -->
<!--   print(n) -->
<!--   for (i in 1:ntrials) { -->

<!--     complete_model_file <- paste0(in.folder,"/imputation_common_",n,"_",i,".hdf5") -->
<!--     incomplete_model_file <- paste0(in.folder,"/imputation_all_",n,"_",i,".hdf5") -->

<!--     if (file.exists(complete_model_file) & file.exists(incomplete_model_file)) { -->
<!--       complete_model <- loadModel(complete_model_file, sortFactors=F) -->
<!--       incomplete_model <- loadModel(incomplete_model_file, sortFactors=F) -->

<!--       # samples <- intersect(sampleNames(complete_model), sampleNames(incomplete_model)) -->

<!--       # Get missing ids -->
<!--       Y_complete <- getTrainData(complete_model, views="Drugs")[[1]] -->
<!--       # ids_complete <- which(is.na(Y_complete), arr.ind = T) -->
<!--       Y_incomplete <- getTrainData(incomplete_model, views="Drugs")[[1]] -->
<!--       # ids_incomplete <- which(is.na(Y_incomplete), arr.ind = T) -->

<!--       samples <- apply(Y_complete,2, function(x) mean(is.na(x))) == 1 -->

<!--       # Calculate predictions in complete data -->
<!--       # Z <- getFactors(complete_model, include_intercept = F) -->
<!--       # SW <- getWeights(complete_model, views="Drugs")[[1]] -->
<!--       # Ypred_complete <- t(Z %*% t(SW))[,samples]  -->
<!--       complete_model <- imputeMissing(complete_model, views = "Drugs") -->
<!--       Ypred_complete <- getImputedData(complete_model)[["Drugs"]] -->

<!--       # Calculate predictions in incomplete data -->
<!--       # Z <- getFactors(incomplete_model, include_intercept = F) -->
<!--       # SW <- getWeights(incomplete_model, views="Drugs")[[1]] -->
<!--       # Ypred_incomplete <- t(Z %*% t(SW))[,samples]       -->
<!--       incomplete_model <- imputeMissing(incomplete_model, views = "Drugs") -->
<!--       Ypred_incomplete <- getImputedData(incomplete_model)[["Drugs"]] -->

<!--       # Compute mean squared error -->
<!--       tmp[nsamples_downsampled==n & trial==i, complete_mse:=mean((Ypred_complete[,samples]-Y[,samples])**2, na.rm=T)] -->
<!--       tmp[nsamples_downsampled==n & trial==i, incomplete_mse:=mean((Ypred_incomplete[,samples]-Y[,samples])**2, na.rm=T)] -->
<!--     } -->

<!--   } -->
<!-- } -->

<!-- # mRNA <- read.table("/Users/ricard/data/CLL/views/minView=2/mRNA.txt", header=T) %>% as.matrix -->
<!-- # nsamples <- sum(apply(mRNA, 1, function(x) mean(is.na(x))) == 0) -->


<!-- tmp2 <- melt(tmp,  measure.vars=c("complete_mse","incomplete_mse"), variable.name="type", value.name="MSE") %>% -->
<!--   .[,c("nsamples_downsampled","trial"):=list(nsamples_downsampled,as.factor(trial))] %>% -->
<!--   .[MSE>0] %>% .[,nsamples_downsampled:=nsamples_downsampled/136] -->

<!-- p <- ggplot(tmp2, aes(x=nsamples_downsampled, y=MSE, group=type, color=type)) + -->
<!--   stat_summary(fun.y="mean", geom="line", size=1) + -->
<!--   stat_summary(fun.data="mean_se", geom="errorbar", width=0.01, alpha=0.6) + -->
<!--   theme_bw() + -->
<!--   labs(x="Downsampling fraction", y="Mean squared error") + -->
<!--   scale_color_discrete(labels=c("Complete data set", "Incomplete data set")) + -->
<!--   scale_x_continuous(breaks=c(0.1,0.2,0.3,0.4,0.5,0.6,0.7)) + -->
<!--   theme( -->
<!--     axis.title= element_text(size=rel(1.7)), -->
<!--     axis.text = element_text(color="black", size=rel(1.3)), -->
<!--     legend.position = "top", -->
<!--     legend.title = element_blank(), -->
<!--     legend.text = element_text(size=rel(1.3)) -->
<!--   ) -->
<!-- # print(p) -->


<!-- # pdf("/Users/ricard/CLL/downsample/out/imputation.pdf", width = 7, height = 4.5) -->
<!-- pdf("/homes/ricard/CLL/downsample/out/imputation.pdf", width = 7, height = 4.5) -->
<!-- print(p) -->
<!-- dev.off() -->
<!-- ``` -->

