---
title: "MOFA: Assessment of the continuity of IGHV factor in the meth data"
output:
  BiocStyle::html_document:
    toc: true
---

```{r}
library(MOFAtools)
library(data.table)
library(purrr)
library(magrittr)
library(dplyr)
library(ggplot2)
library(gridExtra)
```

```{r}
outdir <- "../out"
plotdir <- "figures/"
knitr::opts_chunk$set(fig.path=plotdir, dev=c("png", "pdf"))
```


#Load base model
```{r}
load(file.path(outdir,"out_import.RData"))
idx_ighv <- "1"
```

# Load models without drug data 
```{r}
# needs to be adapted to output folder from the sh scripts
in.folder <- "~/Documents/MOFA/CLL_MOFA_data/out/continuity"

files <- list.files(in.folder, pattern="model_nomet.*\\.hdf5$")
models <- lapply(files, function(fnm) loadModel(file.path(in.folder,fnm), sortFactors = T))
```

# Load patient  data
```{r load_patient_meta, echo=FALSE}
#from the original study Dietrich et al 2018 now at BloodCancerMultiOmics2017
# data(patmeta, package="BloodCancerMultiOmics2017")
data(patmeta, package="PACEdata")
patmeta <- patmeta[sampleNames(models[[1]]),] %>%
  tibble::rownames_to_column("sample") %>%
  as.data.table %>% .[,c("sample","IGHV","ConsClust")] %>%
  setnames("IGHV","ighv_status") %>%
  setnames("ConsClust","MethylationCluster")
```

# Get our clusters from base model and define colors
```{r}
set.seed(32180)
ZMC <- kmeans(Z[,idx_ighv], 3, nstart=1000, iter.max = 1000)
ZMC <- ZMC$cluster
ZMC <- ifelse(ZMC==1, "HZ", ifelse(ZMC==2, "LZ", "IZ"))
ZMC <- as.data.table(ZMC, keep.rownames=TRUE) %>% setnames("rn", "sample")
col4MC <- c(LZ="navy", IZ="darkgoldenrod", HZ="darkred", "missing"="gray")
patmeta  %<>% merge(ZMC,by="sample") 
```

# Load meth data 
```{r}
data("CLL_data")
methData <- CLL_data[["meth"]]

# Convert to data.table
methData <- methData %>% as.data.table(keep.rownames=T) %>% 
  setnames("rn","sample") %>%
  melt(id.vars="sample", variable.name="CpG", value.name="Mvalue")
```


# Collect IGHV factor from the models (it is always factor 1)
```{r}
ighv_factor <- list()
models <- c( models, model)
for (i in 1:length(models)) {
  tmp <- getFactors(models[[i]], factors="1", as.data.frame=T)
  tmp$trial <- i
  if(i==length(models)) tmp$trial <- "full"
  tmp %<>% merge(patmeta,by="sample")
  # Align IGHV factors
  fit <- glm(factor(tmp$ighv_status, levels=c("U", "M")) ~ tmp$value, family="binomial")
  print(summary(fit))
  if(fit$coefficients[2]<0) tmp %<>% mutate(value = -value)
  
  set.seed(32180)
  ZMC_sub <- kmeans(tmp$value, 3, nstart=1000, iter.max = 1000)
  ZMC_sub <- ZMC_sub$cluster
  perms <- permute::allPerms(1:3)
  tt <- table(tmp$MethylationCluster, ZMC_sub)
  xx <- which.max(apply(perms,1, function(x) sum(sapply(1:3, function(i) tt[i,x[i]]))))
  order2use <- perms[xx,]
  
  ZMC_sub <- ifelse(ZMC_sub==order2use[1], "HZ", ifelse(ZMC_sub==order2use[3], "LZ", "IZ"))
  tmp$ZMC_sub <- ZMC_sub
  print(sum(tmp$ZMC_sub != tmp$ZMC))
  
  ighv_factor[[i]] <- tmp
}
ighv_factor <- rbindlist(ighv_factor) %>% .[,factor:=NULL]

ggplot(ighv_factor, aes(y=value, x=1, col=ZMC, shape=ZMC_sub)) + geom_jitter() + facet_wrap(~trial)
ighv_factor_mat <- reshape2::acast(ighv_factor, sample ~ trial)
cor(ighv_factor_mat)

ighv_factor <- filter(ighv_factor, trial != "full")
```


# Scatterplot between IGHV factor and gene expression markers
Only use one trial, as they are all very similar
```{r figure_noMeth, fig.width = 6, fig.height = 2}
# interesting_CpG <- names(tail(sort(abs(model@Expectations$SW$Methylation$E[,idx_ighv])), n=20))
interesting_CpG <- c("cg17479716","cg19358877","cg26615224")

plist <- lapply(interesting_CpG, function(x) {
  tmp <- filter(methData,CpG==x)
  foo <- merge(tmp,ighv_factor,by="sample", allow.cartesian = T) %>% setnames("value","ighv_factor")
  
  p <- ggplot(filter(foo, trial==4), aes(x=ighv_factor, y=Mvalue, group=trial, shape=as.factor(trial))) +
    geom_point(aes(color=ZMC), size=1.25) +
    stat_smooth(method="lm") +
    theme_bw() + ylab(x) +guides(color=F, shape=F)+
    scale_color_manual(values = col4MC) +xlab("IGHV-Factor")
  p
})

grid.arrange(plist[[1]],plist[[2]],plist[[3]], ncol=3)
```

#SessionInfo
```{r}
sessionInfo()
```

