---
title: "Get views for input to MOFA"
output:
  BiocStyle::html_document:
    toc: true
---

```{r, message=F, warning=FALSE}
library(dplyr)
library(DESeq2)
library(data.table)
```


# Set general in/out parameters
```{r}
#input files
RNAseqFile <- "~/Documents/MOFA/CLL_MOFA_data/pace/data/dds.RData"
methFile <- "~/Documents/MOFA/CLL_MOFA_data/pace/data/meth.RData"
DrugResponseFile <- "~/Documents/MOFA/CLL_MOFA_data/pace/data/lpdAll.RData"
PatMetaFile <- "~/Documents/MOFA/CLL_MOFA_data/pace/data/patmeta.RData"
MutationsFile <- "~/Documents/MOFA/CLL_MOFA_data/pace/data/mutCOM.RData"

# minimum number of views observed for a patient to be included 
# Views considered are RNA, Methylation, durg response and mutations
minViews <- 2       #for analysis
minViews <- "all"   #for imputation analysis, iCLuster comparison

#output directory
outDir <- paste("~/Documents/MOFA/CLL_MOFA_data/views/minView=",minViews, sep="")

if(minViews=="all") minViews <- 4

# make output director
if(!dir.exists(outDir))  dir.create(outDir)

# patients to be included (only CLL)
namePatMeta <- load(PatMetaFile)
patmeta <- get(namePatMeta)
patmeta$PatID <- rownames(patmeta)
patCLL <- patmeta %>% filter(Diagnosis=="CLL")
rownames(patCLL) <- patCLL$PatID
```

#Get RNAseq
```{r}
source("getRNAseq.R")

# annotation file from ENSEMBLE (corresponding to GRCh 37.1)
AnnoFileList<-list(
  mRNA= "~/Documents/BioMart/Hsapiens_genes_BioMart.75.txt",
  lincRNA = "~/Documents/BioMart/Hsapiens_lincRNA_BioMart.75.txt",
  miRNA = "~/Documents/BioMart/Hsapiens_miRNA_BioMart.75.txt"
)

RNA <- getRNAseq(file =RNAseqFile, pat2include = patCLL$PatID,
                minrs = 100, AnnoFileList = AnnoFileList, plotit = T,
                outdir = outDir, onlyCD19 = F, topmRNA=5000, noY=T)
```

#Get methylation data
```{r}
source("~/Documents/MOFA/CLL_MOFA_data/views/getMeth.R")
meth <- getMeth(methFile, pat2include = patCLL$PatID,
              Frac2include = 0.01, outdir = outDir, includeXYchr=F,
              methDataFile="zcat < /Users/bvelten/Documents/MOFA/CLL_MOFA_data/methylation/in/met.tsv.gz")
```

#Get drug response 
```{r}
source("~/Documents/MOFA/CLL_MOFA_data/views/getViab.R")

viab <- getViab(file = DrugResponseFile, 
                  pat2include = patCLL$PatID,
                  badDrugs=c( "D_008",  "D_025"), 
                  conc2include = 1:5,
                  maxval = 1.1,
                  outdir = outDir)
```

#Get mutations
```{r}
source("~/Documents/MOFA/CLL_MOFA_data/views/getMut.R")
mut<-getMut(file = MutationsFile, 
                  pat2include = patCLL$PatID,
                  minObs = 3,
                  outdir = outDir)

# add IGHV status to mutations
ighv <- patCLL[rownames(mut),"IGHV"]
ighv <- ifelse(ighv=="U",0,1)
mut <- cbind(mut, IGHV=ighv)
```

# Get covariates
```{r}
source("~/Documents/MOFA/CLL_MOFA_data/views/getCovariates.R")
covariates <- getCovariates(file = PatMetaFile,
              pat2include = patCLL$PatID,
              cov2include = c("Gender", "Diagnosis"),
              outdir = outDir)
```

#Overview Sampler per Omic
```{r}
PatPerView <- lapply(list(RNA=RNA[[1]], meth=meth, viab=viab, mut=mut, covariates = covariates), rownames)
gplots::venn(PatPerView)
```


# Take union of all patients
```{r}
unionPats<-Reduce(union, PatPerView)
subset_augment<-function(mat, pats) {
  aug_mat<-matrix(NA, ncol=ncol(mat), nrow=length(pats))
  aug_mat<-mat[match(pats,rownames(mat)),,drop=FALSE]
  rownames(aug_mat)<-pats
  colnames(aug_mat)<-colnames(mat)
  return(aug_mat)
}
viab_aug<-subset_augment(viab, pats=unionPats)
meth_aug<-subset_augment(meth, pats=unionPats)
mut_aug<-subset_augment(mut, pats=unionPats)
RNA_aug<-lapply(RNA, function(RNAsub) subset_augment(RNAsub, pats=unionPats))
covariates_aug <- subset_augment(covariates, pats=unionPats)
```

##Save views with samples having at least minViews
```{r}
CLL_aug <- list(mRNA = RNA_aug$mRNA, viab = viab_aug, meth= meth_aug, mut =mut_aug)
observedViewsPerPat <- rowSums(sapply(CLL_aug, function(dat) !apply(is.na(dat),1,all)))
patsWithminViews <- observedViewsPerPat >= minViews
patsWithminViews <- names(patsWithminViews)[patsWithminViews]

# write to txt files for MOFA input
write.table(viab_aug[patsWithminViews,], file=file.path(outDir,"viab.txt"),
                row.names=TRUE, col.names=TRUE, quote=F)
write.table(meth_aug[patsWithminViews,], file=file.path(outDir,"meth.txt"),
                row.names=TRUE, col.names=TRUE, quote=F)
write.table(mut_aug[patsWithminViews,], file=file.path(outDir,"mut.txt"),
                row.names=TRUE, col.names=TRUE, quote=F)
write.table(covariates_aug[patsWithminViews,], file=file.path(outDir,"covariates.txt"),
                row.names=TRUE, col.names=TRUE, quote=F)
for(nm in names(RNA_aug)) write.table(RNA_aug[[nm]][patsWithminViews,],
                                        file=file.path(outDir,paste(nm,".txt", sep="")),
                                        row.names=TRUE, col.names=TRUE, quote=F)
```
