---
title: "MOFA Simulations: analysis of element-wise spike-slab sparsity"
author: "Ricard Argelaguet"
date: "`r Sys.Date()`"
output:
  BiocStyle::html_document:
    toc: true
---

```{r}
devtools::load_all("/Users/ricard/mofa/MOFAtools")
# library(MOFAtools)
library(data.table)
library(purrr)
library(ggplot2)
```

```{r}
theme_fn <- function() {
    theme(
    # plot.title = element_text(size=titlesize),
    plot.margin = margin(10,10,10,10),
    axis.title.x=element_text(colour="black",size=rel(1.75), margin=margin(20,0,3,0)),
    axis.title.y=element_text(colour="black",size=rel(1.75), margin=margin(0,20,0,3)),
    axis.text.x=element_text(colour="black",size=rel(1.5)),
    axis.text.y=element_text(colour="black",size=rel(1.5)),
    axis.ticks.x = element_line(colour="black"),
    axis.ticks.y = element_line(colour="black"),
    axis.line.x = element_line(color="black"),
    axis.line.y = element_line(color="black"),
    legend.position="top",
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank()
  )
}
```

```{r}
in.folder <- "/Users/ricard/data/MOFA/simulations/26Aug/data/D"
D_list <- c(5000,10000)
ntrials <- 10
views <- "0"
```

<!-- Load true weights -->
```{r}
in.folder <- "/Users/ricard/data/MOFA/simulations/26Aug/data/D"

weights_list <- list()
for (d in D_list) {
  for (trial in seq(0,ntrials-1)) {
    weights_list[[paste0(d,"_",trial)]] <- list()  
    for (m in views) {
      weights_list[[paste0(d,"_",trial)]][[m]] <- fread(paste0(in.folder,"/trial",trial,"/",d,"_W_",m,".txt")) %>% as.matrix
    }
  }
}
```

<!-- Load true latent variables -->
```{r}
in.folder <- "/Users/ricard/data/MOFA/simulations/26Aug/data/D"

factors_list <- list()
for (d in D_list) {
  for (trial in seq(0,ntrials-1)) {
    factors_list[[paste0(d,"_",trial)]] <- fread(paste0(in.folder,"/trial",trial,"/",d,"_Z.txt")) %>% as.matrix
  }
}
```

<!-- Load data and fit PCA solution -->
```{r}

pca_models <- list()
for (d in D_list) {
  for (trial in seq(0,ntrials-1)) {
    data_list <- list()
    for (m in views) {
      data_list[[m]] <- fread(paste0(in.folder,"/trial",trial,"/",d,"_",m,".txt")) %>% as.matrix
    }
    data <- do.call("cbind",data_list)
    pca_models[[paste0(d,"_",trial)]] <- pcaMethods::pca(data, nPcs=10, center=T, scale="none")
  }
}

```

<!-- Load sparse models -->
```{r}
in.folder <- "/Users/ricard/data/MOFA/simulations/26Aug/results/sparse/D"
files <- list.files(in.folder, pattern=".hdf5$")
sparse_models <- list()
for (i in 1:length(files)) {
  split <- strsplit(files[i],"_")[[1]]
  d <- split[2]
  trial <- substr(split[[3]],1,nchar(split[[3]])-5)
  sparse_models[[paste(d,trial,sep="_")]] <- loadModel(paste0(in.folder,"/",files[i]))
}
```

<!-- Load non-sparse models -->
```{r}
in.folder <- "/Users/ricard/data/MOFA/simulations/26Aug/results/nonsparse/D"
files <- list.files(in.folder, pattern=".hdf5$")
nonsparse_models <- list()
for (i in 1:length(files)) {
  split <- strsplit(files[i],"_")[[1]]
  d <- split[2]
  trial <- substr(split[[3]],1,nchar(split[[3]])-5)
  nonsparse_models[[paste(d,trial,sep="_")]] <- loadModel(paste0(in.folder,"/",files[i]))
}
```

<!-- Extract infered weights from the model -->
```{r}

# PCA model
pca_weights <- list()
for (i in names(pca_models)) {
  d <- strsplit(i,"_")[[1]][1]
  trial <- strsplit(i,"_")[[1]][2]
  pca_weights[[i]] <- pca_models[[i]]@scores %>% as.data.table %>%
    .[,c("feature","trial","D","view"):=list(1:nrow(.),trial,paste0("D=",d),"all")] %>%
    melt(id.vars=c("feature","trial","D","view"), variable.name="factor") %>% 
    .[,c("feature","factor","value","view","D","trial")]
}
pca_weights <- pca_weights %>% rbindlist %>% .[,type:="Concatenated PCA"]


# Spike and slab model
sparse_weights <- list()
for (i in names(sparse_models)) {
  split <- strsplit(i,"_")[[1]]
  d <- split[1]
  trial <- split[2]
  tmp <- getWeights(sparse_models[[i]], as.data.frame=T) %>% as.data.table %>% .[,c("D","trial"):=list(paste0("D=",d), trial) ]
  
  # Select all factors and views which are active
  # R2 <- calculateVarianceExplained(sparse_models[[i]], plotit=F)$R2PerFactor
  # sparse_weights[[i]] <- lapply(unique(tmp$factor), function(k) tmp[factor==k & view%in%names(which(R2[k,]>0.01))] ) %>% rbindlist
  sparse_weights[[i]] <- tmp
}
sparse_weights <- sparse_weights %>% rbindlist %>% .[,type:="Spike and Slab"]

# ARD model
nonsparse_weights <- list()
for (i in names(nonsparse_models)) {
  split <- strsplit(i,"_")[[1]]
  d <- split[1]
  trial <- split[2]
  tmp <- getWeights(nonsparse_models[[i]], as.data.frame=T) %>% as.data.table %>% .[,c("D","trial"):=list(paste0("D=",d), trial) ]
  
  # Select all factors and views which are active
  # R2 <- calculateVarianceExplained(nonsparse_models[[i]], plotit=F)$R2PerFactor
  # nonsparse_weights[[i]] <- lapply(unique(tmp$factor), function(k) tmp[factor==k & view%in%names(which(R2[k,]>0.01))] ) %>% rbindlist
  nonsparse_weights[[i]] <- tmp
}
nonsparse_weights <- nonsparse_weights %>% rbindlist %>% .[,type:="ARD"]

weights <- rbind(pca_weights, sparse_weights, nonsparse_weights)
```


# Correlation with true weights
```{r}

zero_threshold <- 1e-3
models <- names(weights_list)

dt_sparse <- list()
dt_nonsparse <- list()
dt_pca <- list()
for (model in models) {
  print(model)
  d <- as.numeric(strsplit(model,"_")[[1]][1])
  trial <- strsplit(model,"_")[[1]][2]
  
  # True weights and factors
  true_weights <- weights_list[[model]][["0"]]
  true_factors <- factors_list[[model]]
  
  # Sparse model weights
  if (!is.null(nonsparse_models[[model]])) {
    R2 <- calculateVarianceExplained(sparse_models[[model]], plotit=F)$R2PerFactor[,"0"]
    sparse_active_factors <- as.character(which(R2>0.03))
    infered_weights <- getWeights(sparse_models[[model]])[["0"]][,sparse_active_factors]
    infered_factors <- getFactors(sparse_models[[model]], factors = sparse_active_factors)
    # r <- cor(abs(true_weights),abs(infered_weights))
    r <- cor(true_factors,infered_factors)
    dt_sparse[[model]] <- data.table(model="sparse", D=d, trial=trial, factor=sparse_active_factors, mean=0, cor=0)
    for (k in sparse_active_factors) {
      kk <- which.max(r[,k])
      # dt_sparse[[model]][factor==k, mean:=mean( (abs(true_weights[,kk])<zero_threshold)==(abs(infered_weights[,k])<zero_threshold) )]
      dt_sparse[[model]][factor==k, mean:=length(intersect(which(abs(true_weights[,kk])<zero_threshold), which(abs(infered_weights[,k])<zero_threshold) ))/d]
      dt_sparse[[model]][factor==k, cor:=cor(abs(true_weights[,kk]),abs(infered_weights[,k]))]
    }
  }
  
  # Non-sparse model
  if (!is.null(nonsparse_models[[model]])) {
    R2 <- calculateVarianceExplained(nonsparse_models[[model]], plotit=F)$R2PerFactor[,"0"]
    nonsparse_active_factors <- as.character(which(R2>0.03))
    bar2 <- getWeights(nonsparse_models[[model]])[["0"]][,nonsparse_active_factors]
    r <- cor(abs(true_weights),abs(bar2))
    dt_nonsparse[[model]] <- data.table(model="nonsparse", D=d, trial=trial, factor=nonsparse_active_factors, mean=0, cor=0)
    for (k in nonsparse_active_factors) {
      kk <- which.max(r[,k])
      # dt_nonsparse[[model]][factor==k, mean:=mean( (abs(true_weights[,kk])<zero_threshold)==(abs(bar2[,k])<zero_threshold) )]
      dt_nonsparse[[model]][factor==k, mean:=length(intersect(which(abs(true_weights[,kk])<zero_threshold), which(abs(bar2[,k])<zero_threshold) ))/d]
      dt_nonsparse[[model]][factor==k, cor:=cor(abs(true_weights[,kk]),abs(bar2[,k]))]
    }
  }
  
  # PCA weights
  bar3 <- pca_models[[model]]@loadings[1:d,]
  r <- cor(abs(true_weights),abs(bar3))
  dt_pca[[model]] <- data.table(model="pca", D=d, trial=trial, factor=1:ncol(r), mean=0, cor=0)
  for (k in 1:ncol(r)) {
    kk <- which.max(r[,k])
    # dt_pca[[model]][factor==k, mean:=mean( (abs(true_weights[,kk])<zero_threshold)==(abs(bar3[,k])<zero_threshold) )]
    dt_pca[[model]][factor==k, mean:=length(intersect(which(abs(true_weights[,kk])<zero_threshold), which(abs(bar3[,k])<zero_threshold) ))/d]
    dt_pca[[model]][factor==k, cor:=cor(abs(true_weights[,kk]),abs(bar3[,k]))]
  }
  
}

dt <- rbind(rbindlist(dt_sparse), rbindlist(dt_nonsparse), rbindlist(dt_pca))


p <- ggplot(dt, aes(x=model, y=mean)) +
  geom_boxplot(aes(fill=model), alpha=0.5) +
  ggbeeswarm::geom_quasirandom(aes(color=model)) +
  facet_wrap(~D) +
  labs(x="", y="Fraction of true zero weights recovered") +
  theme_bw() + theme(
    plot.margin = margin(10,10,10,10),
    axis.title.x=element_text(colour="black",size=rel(1.75), margin=margin(20,0,3,0)),
    axis.title.y=element_text(colour="black",size=rel(1.75), margin=margin(0,20,0,3)),
    axis.text.x=element_text(colour="black",size=rel(1.5)),
    axis.text.y=element_text(colour="black",size=rel(1.5)),
    axis.ticks.x = element_line(colour="black"),
    axis.ticks.y = element_line(colour="black"),
    axis.line.x = element_line(color="black"),
    axis.line.y = element_line(color="black"),
    legend.position="top",
    legend.title = element_blank(),
    legend.key = element_rect(fill = 'white', linetype='solid'),
    legend.text = element_text(size=rel(1.5))
    # legend.key.width = unit(1.5,"line"),
    # legend.key.height = unit(2,"inch"),
    # legend.key.size = unit(2,"inch"),
  )
print(p)

p <- ggplot(dt, aes(x=model, y=cor)) +
  geom_boxplot(aes(fill=model), alpha=0.5) +
  ggbeeswarm::geom_quasirandom(aes(color=model)) +
  labs(x="", y="Correlation with true weights") +
  facet_wrap(~D) +
  theme_bw()
print(p)
```


# Identification of top weights
```{r}

# True weights
foo <- weights_list[["5000"]][["0"]]

# Sparse model weights
R2 <- calculateVarianceExplained(sparse_models[["5000_0"]], plotit=F)$R2PerFactor[,"0"]
sparse_active_factors <- as.character(which(R2>0.05))
bar1 <- getWeights(sparse_models[["5000_0"]], views = "0")[,sparse_active_factors]

# Non-sparse model weights
R2 <- calculateVarianceExplained(nonsparse_models[["5000_0"]], plotit=F)$R2PerFactor[,"0"]
nonsparse_active_factors <- as.character(which(R2>0.05))
bar2 <- getWeights(nonsparse_models[["5000_0"]], views = "0")[,nonsparse_active_factors]

foo_dt <- foo %>% as.data.table %>% setnames(as.character(1:ncol(.))) %>% 
  .[,feature:=as.factor(1:nrow(.))] %>% melt(id.vars="feature", variable.name="factor")
bar1_dt <- bar1 %>% as.data.table %>% .[,feature:=as.factor(1:nrow(.))] %>%
  melt(id.vars="feature", variable.name="factor")
bar2_dt <- bar2 %>% as.data.table %>% setnames(as.character(1:ncol(.))) %>%
  .[,feature:=as.factor(1:nrow(.))] %>% melt(id.vars="feature", variable.name="factor")

## Plot rank ##
foo_dt_tmp <- foo_dt[factor=="1"] %>% .[value>0] %>%
  .[,value:=abs(value)] %>% setkey(value) %>% .[,rank:=rank(-value, ties.method="min")]

bar1_dt_tmp <- bar1_dt[factor==names(which.max(cor(abs(foo),abs(bar1))[1,]))] %>% 
  .[,value:=abs(value)] %>% setkey(value) %>% .[,rank_sparse:=rank(-value, ties.method="min")]
bar2_dt_tmp <- bar2_dt[factor==names(which.max(cor(abs(foo),abs(bar2))[1,]))] %>% 
  .[,value:=abs(value)] %>% setkey(value) %>% .[,rank_nonsparse:=rank(-value, ties.method="min")]


tmp <- merge(foo_dt_tmp[value>0.01,c("feature","rank")], bar1_dt_tmp[value>0.01,c("feature","rank_sparse")], by=c("feature")) %>%
  merge(bar2_dt_tmp[value>0.01,c("feature","rank_nonsparse")], by="feature") %>%
  melt(id.vars=c("feature","rank"), variable.name="type", value.name="predicted_rank")

p1 <- ggplot(tmp, aes(x=rank, y=predicted_rank, color=type)) +
  geom_smooth(aes(group=type), method="loess")
  # geom_point()
  
print(p1)

## Plot top features of factor 1 ##

# True 
foo_dt_tmp <- foo_dt[factor=="1"] %>% .[,value:=abs(value)] %>% setkey(value) %>% tail(n=10) %>%
  .[,feature:=factor(feature,levels=feature)]
p1 <- ggplot(foo_dt_tmp, aes(x=feature, y=value)) +
  geom_point(size=2) +
  geom_segment(aes(xend=feature, yend=0), size=0.75) +
  scale_colour_gradient(low="grey", high="black") +
  # scale_colour_manual(values=c("#F8766D","#00BFC4")) +
  # guides(colour = guide_legend(title.position="top", title.hjust = 0.5)) +
  coord_flip()
print(p1)

# Sparse
bar1_dt_tmp <- bar1_dt[factor==names(which.max(cor(abs(foo),abs(bar1))[1,]))] %>% 
  .[,value:=abs(value)] %>% setkey(value) %>% tail(n=10) %>%
  .[,feature:=factor(feature,levels=feature)]
p2 <- ggplot(bar1_dt_tmp, aes(x=feature, y=value)) +
  geom_point(size=2) +
  geom_segment(aes(xend=feature, yend=0), size=0.75) +
  scale_colour_gradient(low="grey", high="black") +
  # scale_colour_manual(values=c("#F8766D","#00BFC4")) +
  # guides(colour = guide_legend(title.position="top", title.hjust = 0.5)) +
  coord_flip()
print(p2)

# Non-sparse
bar2_dt_tmp <- bar1_dt[factor==names(which.max(cor(abs(foo),abs(bar2))[1,]))] %>% 
  .[,value:=abs(value)] %>% setkey(value) %>% tail(n=10) %>%
  .[,feature:=factor(feature,levels=feature)]
p3 <- ggplot(bar2_dt_tmp, aes(x=feature, y=value)) +
  geom_point(size=2) +
  geom_segment(aes(xend=feature, yend=0), size=0.75) +
  scale_colour_gradient(low="grey", high="black") +
  # scale_colour_manual(values=c("#F8766D","#00BFC4")) +
  # guides(colour = guide_legend(title.position="top", title.hjust = 0.5)) +
  coord_flip()
print(p3)
cowplot::plot_grid(plotlist=list(p1,p2,p3), nrow=1, ncol=3)
```

# Boxplot of absolute value of weights per factor
```{r, fig.height=8, fig.width=8}


# ggplot(weights, aes(x=type, y=value)) +
#   geom_boxplot(aes(fill=view)) +
#   # scale_y_continuous(limits = c(-0.2,0.2)) +
#   facet_wrap(~D, scales = "free") +
#   theme_fn()
```

# Probability density function of weights
```{r}

# weights[,log:=abs(log10(abs(value)+0.0001))] %>% .[,log:=log*sign(value)]
# p <- ggplot(weights, aes(x=log)) +
#   geom_density(aes(fill=type)) +
#   # scale_y_continuous(limits = c(0,20)) +
#   facet_wrap(~D, scales = "free_y") +
#   theme_fn()
# print(p)


# p <- ggplot(weights, aes(x=value)) +
#   geom_density(aes(fill=type)) +
#   # scale_y_continuous(limits = c(0,20)) +
#   facet_wrap(~D, scales = "free_y") +
#   theme_fn()
# print(p)

p <- ggplot(weights[D=="D=1000"], aes(x=value)) +
  geom_density(aes(fill=type), alpha=0.5) +
  labs(x="Weight", y="Density") +
  theme_bw() + theme(
    plot.margin = margin(10,10,10,10),
    axis.title.x=element_text(colour="black",size=rel(1.75), margin=margin(20,0,3,0)),
    axis.title.y=element_text(colour="black",size=rel(1.75), margin=margin(0,20,0,3)),
    axis.text.x=element_text(colour="black",size=rel(1.5)),
    axis.text.y=element_text(colour="black",size=rel(1.5)),
    axis.ticks.x = element_line(colour="black"),
    axis.ticks.y = element_line(colour="black"),
    axis.line.x = element_line(color="black"),
    axis.line.y = element_line(color="black"),
    legend.position="top",
    legend.title = element_blank(),
    legend.key = element_rect(fill = 'white', linetype='solid'),
    legend.text = element_text(size=rel(1.5))
    # legend.key.width = unit(1.5,"line"),
    # legend.key.height = unit(2,"inch"),
    # legend.key.size = unit(2,"inch"),
  )
print(p)

pdf("/Users/ricard/CLL/simulations/elementwise_sparsity/out/pdf.pdf", width=7, height=5, useDingbats = F)
print(p)
dev.off()
```

# Cumulative density function of weights
```{r}
p <- ggplot(weights[D=="D=5000"], aes(x=value)) +
# p <- ggplot(weights[D=="D=1000" & type%in%c("sparse","nonsparse")], aes(x=value)) +
  stat_ecdf(aes(group=interaction(trial,type), color=type), geom = "step") +
  theme_bw() +
  guides(colour = guide_legend(override.aes = list(size=1.5))) +
  scale_x_continuous(limits=c(-1,1)) +
  labs(y="Cumulative density", x="Weights") +
  theme(
    plot.margin = margin(10,10,10,10),
    axis.title.x=element_text(colour="black",size=rel(1.75), margin=margin(20,0,3,0)),
    axis.title.y=element_text(colour="black",size=rel(1.75), margin=margin(0,20,0,3)),
    axis.text.x=element_text(colour="black",size=rel(1.5)),
    axis.text.y=element_text(colour="black",size=rel(1.5)),
    axis.ticks.x = element_line(colour="black"),
    axis.ticks.y = element_line(colour="black"),
    axis.line.x = element_line(color="black"),
    axis.line.y = element_line(color="black"),
    legend.position="top",
    legend.title = element_blank(),
    legend.key = element_rect(fill = 'white', linetype='solid'),
    legend.text = element_text(size=rel(1.5))
    # legend.key.width = unit(1.5,"line"),
    # legend.key.height = unit(2,"inch"),
    # legend.key.size = unit(2,"inch"),
  )
print(p)

# pdf("/Users/ricard/CLL/simulations/elementwise_sparsity/out/cdf.pdf", width=7, height=5, useDingbats = F)
# print(p)
# dev.off()

```

<!-- # Example of heatmaps -->
<!-- ```{r} -->
<!-- tmp1 <- pca_models[["1000"]]@scores -->
<!-- pheatmap::pheatmap(tmp1) -->

<!-- tmp2 <- do.call("cbind", getWeights(sparse_models[["1000_0"]])) -->

<!-- tmp3 <- do.call("cbind", getWeights(nonsparse_models[["1000_0"]])) -->

<!-- tmp <- cbind(tmp2,tmp3) -->
<!-- pheatmap::pheatmap(tmp2, cluster_rows = F, cluster_cols = F) -->
<!-- pheatmap::pheatmap(tmp3, cluster_rows = F, cluster_cols = F) -->
<!-- ``` -->


<!-- # Calculate kurtosis -->
<!-- Intuitively, the kurtosis describes the tail shape of the data distribution. The normal distribution has zero kurtosis. -->
<!-- Negative kurtosis would indicate a thin-tailed data distribution. -->
<!-- Positive kurtosis would indicate a fat-tailed distribution, and is said to be leptokurtic. -->
<!-- ```{r} -->
<!-- library(e1071) -->
<!-- kurtosis(weights[[1]][,7]) -->
<!-- ``` -->

