---
title: "Iou"
output:
  BiocStyle::html_document:
    toc: true
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
devtools::load_all("/Users/ricard/mofa/MOFAtools")
library(data.table)
library(purrr)
library(ggplot2)
```

<!-- Load fitted model_all -->
```{r}
model_all <- loadModel(file = "/Users/ricard/data/CLL/out/imputation/examples/drug_masked_all.hdf5")
model_subset <- loadModel(file = "/Users/ricard/data/CLL/out/imputation/examples/old/drug_masked.hdf5")


# Samples to mask
samples_tomask <- c("H050","H235","H170","H236","H135","H042","H164","H012","H252","H211")

# Features to mask
features_tomask <- c(
  "D_078_1", "D_078_2", "D_078_3", "D_078_4", "D_078_5",
  "D_020_1", "D_020_2", "D_020_3", "D_020_4", "D_020_5",
  "D_017_1", "D_017_2", "D_017_3", "D_017_4", "D_017_5",
  # "D_050_1", "D_050_2", "D_050_3", "D_050_4", "D_050_5",
  "D_077_1", "D_077_2", "D_077_3", "D_077_4", "D_077_5"
  )

getTrainData(model_all, views="Drugs")[features_tomask,samples_tomask]
getTrainData(model_subset, views="Drugs")[features_tomask,samples_tomask]
```
 
<!-- Load ground truth data -->
```{r}
drugData <- read.table("/Users/ricard/data/CLL/views/minView=2/viab.txt")
```

<!-- Calculate variance explained -->
```{r}
# varExplained <- calculateVarianceExplained(model_all, plotit = T)
# print(varExplained)
```

<!-- Impute using MOFA -->
```{r}

# DOES NOT WORK, FIX
# model_all_i <- imputeMissing(model_all, views="Drugs")

model_all_i <- imputeMissing(model_all, views="all")
model_subset_i <- imputeMissing(model_subset, views="all")
```

```{r}
W <- getWeights(model_all, views="Drugs", factors="all")[[1]]
Z <- getFactors(model_all)
Ypred <- Z %*% t(W)
Ypred["H050","D_017_1"]

W <- getWeights(model_subset, views="Drugs", factors="all")[[1]]
Z <- getFactors(model_subset)
Ypred <- Z %*% t(W)
Ypred["H050","D_017_1"]
```

<!-- Merge imputation with ground truth -->
```{r}
foo <- getImputedData(model_all_i, views="Drugs", as.data.frame = T) %>% as.data.table %>% .[,view:=NULL] %>% setnames("value","predicted_all")
bar <- getImputedData(model_subset_i, views="Drugs", as.data.frame = T) %>% as.data.table %>% .[,view:=NULL] %>% setnames("value","predicted_subset")
baz <- drugData %>% as.data.table(keep.rownames = T) %>% setnames("rn","sample") %>% melt(id.vars="sample", value.name="true", variable.name="feature")
foobarbaz <- merge(foo,bar, by=c("sample","feature")) %>% merge(baz,by=c("sample","feature"))

foo[sample=="H050" & feature=="D_017_1"]
foobarbaz[sample=="H050" & feature=="D_017_1"]
```

<!-- Impute via mean -->
```{r}
foobarbaz[,mean:=mean(true,na.rm=T), by=c("feature")]
```

<!-- Plot predicted vs true -->
```{r, fig.height=6, fig.width=8}
tmp <- foobarbaz[sample%in%samples_tomask & feature%in%features_tomask] %>%
  .[,feature:=as.character(feature)] %>%
  .[,drug:=sapply(strsplit(feature, "_"), function(l) paste0(l[1],l[2]))] %>%
  .[,conc:=sapply(strsplit(feature, "_"), function(l) l[3])] %>%
  melt(value.vars=c("predicted","true"), variable.name="type")

p <- ggplot(tmp[sample%in%c("H050","H042")], aes(x=conc, y=1-value, color=type, group=interaction(type,sample))) +
  geom_point(size=2) + 
  geom_line(aes(linetype=sample), size=1) +
  facet_wrap(~drug, nr=2,nc=2, scales = "fixed") +
  # scale_y_continuous(limits=c(0,1)) +
  labs(x="Concentration", y="Cellular viability") +
  theme_bw() +
  theme(
    axis.text = element_text(size = rel(1.5), color = "black"),
    axis.title.y = element_text(size = rel(2.0), margin = margin(0, 15, 0, 0)),
    axis.title.x = element_text(size = rel(2.0), margin = margin(15, 0, 0, 0)),
    axis.line = element_line(colour = "black", size = 0.5),
    axis.ticks = element_line(colour = "black", size = 0.5),
    legend.key = element_rect(fill = "white"),
    legend.position = "top",
    strip.text = element_text(size=rel(2.0)),
    legend.text = element_text(size = rel(1.2)),
    legend.title = element_text(size = rel(1.5))
  )
print(p)

pdf("/Users/ricard/MOFA_CLL/imputation/examples/out/asd.pdf", width = 8, height = 6.5)
print(p)
dev.off()
```


