---
title: " Comparison of MOFA vs PCA"
output:
  BiocStyle::html_document:
    toc: true
---

```{r, warning=FALSE, message=FALSE}
devtools::load_all("/Users/ricard/mofa/MOFAtools")
# library(MOFAtools)
library(dplyr)
library(tidyr)
library(ggplot2)
```

```{r}
plotFactorVsPC <- function(object, view, factors = "all", nPCs = 5, method = "svd", impute_missing = F, ...) {
  
  # sanity checks
  if (class(object) != "MOFAmodel") stop("'object' has to be an instance of MOFAmodel")
  
  # Fetch factors
  if (paste0(factors,collapse="") == "all") { 
    factors <- factorNames(object) 
  } else if (is.numeric(factors)) {
    factors <- factorNames(object)[factors]
  } else { 
    stopifnot(all(factors %in% factorNames(object))) 
  }
  Z <- getFactors(object)[,factors]
  
  # If present, temove intercept
  if (object@ModelOpts$learnIntercept==TRUE)
    Z <- Z[,colnames(Z)!="intercept"]
  
  # Fetch data
  data <- getTrainData(object,view)[[1]]
  
  # Replace NaN by NA
  data[is.nan(data)] <- NA
  
  # Impute missing data
  # if (impute_missing==T) {
  #   data <-
  # }
  
  # Remove missing samples
  stopifnot(colnames(data) == rownames(Z))
  samples <- apply(data,2, function(x) mean(is.na(x))) < 1
  data <- data[,samples]
  Z <- Z[samples,]
  colnames(Z) = paste0("MOFA_Factor",colnames(Z))
  
  # Perform PCA
  pc.out <- pcaMethods::pca(t(data), method=method, center=TRUE, scale="none", nPcs=nPCs)
  
  # Extract principal components
  pcs <- t(pc.out@scores)
  rownames(pcs) <- paste(m, rownames(pcs), sep="_")
  
  # Calculate correlation matrix between latent factors and PCs
  r <- cor(t(pcs), Z, use="complete.obs")
  
  # Plot correlation matrix
  # corrplot::corrplot(t(r), order="original", title="", tl.col="black", mar=c(1,1,3,1))
  corrplot::corrplot(t(abs(r)), order="original", tl.col="black", ...)
  
  return(r)
}
```

<!-- Define I/O and options -->
```{r}
io <- list()
io$outdir <- "/Users/ricard/mofa_rebuttal/mofa_vs_pca/out"

opts <- list()
opts$views <- c("Drugs","Methylation","mRNA")
```

<!-- Load data -->
```{r}
data("CLL_data")
```

<!-- Run MOFA for each view separately -->
```{r}
mofa_models <- list()
for (i in opts$views) {
  mofa_models[[i]] <- createMOFAobject(CLL_data[i])
  
  # Define I/O options
  DirOptions <- list("dataDir" = tempdir(), "outFile" = paste0(io$outdir, "/",i,".hdf5"))
    
  # Define data options
  DataOptions <- getDefaultDataOpts()
  
  # Define training options
  TrainOptions <- getDefaultTrainOpts()
  TrainOptions$learnFactors <- F
  
  # Define model options  
  ModelOptions <- getDefaultModelOpts(mofa_models[[i]])
  ModelOptions$numFactors <- 10
    
  # Prepare MOFA object for training
  mofa_models[[i]] <- prepareMOFA(mofa_models[[i]], DataOptions = DataOptions, DirOptions = DirOptions,
                     ModelOptions = ModelOptions, TrainOptions = TrainOptions)
    
  # Run MOFA
  mofa_models[[i]] <- runMOFA(mofa_models[[i]], DirOptions, mofaPath="/Users/ricard/anaconda2/bin/mofa")
}
```

<!-- Compare MOFA factors to PCA principal components -->
Missing values are imputed by feature-wise mean
```{r}
pdf(paste0(io$outdir,"/drugs_mofapcs.pdf"), useDingbats = F, width=6, height=6)
plotFactorVsPC(mofa_models[["Drugs"]], view="Drugs", factors="all", nPCs = 10, title="Drug response view")  
dev.off()

pdf(paste0(io$outdir,"/mrna_mofapcs.pdf"), useDingbats = F, width=6, height=6)
plotFactorVsPC(mofa_models[["mRNA"]], view="mRNA", factors="all", nPCs = 10, title="mRNA view") 
dev.off()

pdf(paste0(io$outdir,"/methylation_mofapcs.pdf"), useDingbats = F, width=6, height=6)
plotFactorVsPC(mofa_models[["Methylation"]], view="Methylation", factors="all", nPCs = 10, title="Methylation view")  
dev.off()

# plotFactorVsPC(mofa_models[["Mutations"]], view="Mutations", factors="all", nPCs = 10, title="Methylation view")  
```

<!-- Compare weight vectors of PC and MOFA models -->

The weights coming from PCA and MOFA are not necessarily in the same scale, how to normalise them?
```{r}

view <- "mRNA"
nPCs <- 10
method <- "bpca"

# Fetch MOFA weights
W_mofa <- getWeights(mofa_models[[view]], as.data.frame = T)
W_mofa <- W_mofa %>% filter(factor != "intercept") %>% select(c("feature","factor","value")) %>% mutate(model="mofa")

# Fetch PCA weights
data <- getTrainData(mofa_models[[view]],view)[[1]]
# data[is.nan(data)] <- NA
data <- data[,apply(data,2, function(x) mean(is.na(x))) < 1]
pc.out <- pcaMethods::pca(t(data), method=method, center=TRUE, scale="none", nPcs=nPCs)
W_pca <- pc.out@loadings %>% as.data.frame %>% mutate(feature=rownames(pc.out@loadings)) %>%
  gather(key="factor", value="value",-feature) %>% mutate(model="pca")

# Concatenate both
W <- rbind(W_mofa, W_pca)

# Plot
p <- ggplot(W, aes(x=value)) +
  stat_ecdf(aes(group=interaction(factor,model), color=model), geom = "step") +
  theme_bw() +
  # guides(colour = guide_legend(override.aes = list(size=1.5))) +
  # scale_x_continuous(limits=c(-1,1)) +
  labs(y="Cumulative density", x="Weights") +
  theme(
    plot.margin = margin(10,10,10,10),
    axis.title.x=element_text(colour="black",size=rel(1.75), margin=margin(20,0,3,0)),
    axis.title.y=element_text(colour="black",size=rel(1.75), margin=margin(0,20,0,3)),
    axis.text.x=element_text(colour="black",size=rel(1.5)),
    axis.text.y=element_text(colour="black",size=rel(1.5)),
    axis.ticks.x = element_line(colour="black"),
    axis.ticks.y = element_line(colour="black"),
    axis.line.x = element_line(color="black"),
    axis.line.y = element_line(color="black"),
    legend.position="top",
    legend.title = element_blank(),
    legend.key = element_rect(fill = 'white', linetype='solid'),
    legend.text = element_text(size=rel(1.5))
    # legend.key.width = unit(1.5,"line"),
    # legend.key.height = unit(2,"inch"),
    # legend.key.size = unit(2,"inch"),
  )
print(p)
```

