---
title: "MOFA - comparison to iCluster"
author: "Britta Velten"
date: "28 March 2018"
output:
  BiocStyle::html_document:
    toc: true
---

```{r, warning=F, message=F}
library(MOFAtools)
library(dplyr)
library(reshape2)
library(pheatmap)
library(ggplot2)
library(glmnet)
library(survival)
library(cowplot)
library(iClusterPlus)
```

```{r}
knitr::opts_chunk$set(fig.width = 5, fig.height = 5)
```

```{r}
datadir <- "/Volumes/huber/users/bvelten/tmp/iCluster/CLL/imputed/fits/"
```

# Data
```{r, echo=F}
impute <- function(d, margin) {
  if (margin == 1)
    means <- rowMeans(d, na.rm=T)
  else if (margin == 2)
    means <- colMeans(d, na.rm=T)
  else
    stop("Margin has to be either 1 (rows) or 2 (cols)")
  
  if (any(is.na(means))) {
    stop('Insufficient data for mean imputation!')
  }
  
  for (i in 1:length(means)) {
    if (margin == 1)
      d[i,is.na(d[i,])] <- means[i]
    else if (margin == 2)
      d[is.na(d[,i]), i] <- means[i]
  }
  return (d)
}
```

```{r}
# Load data
data("CLL_data")
CLL_data <- lapply(CLL_data,t)

# Impute missing data
CLL_data[["Drugs"]] <- impute(CLL_data[["Drugs"]], margin = 2)
CLL_data[["mRNA"]] <- impute(CLL_data[["mRNA"]], margin = 2)
CLL_data[["Methylation"]] <- impute(CLL_data[["Methylation"]], margin = 2)
CLL_data[["Mutations"]] <- round(impute(CLL_data[["Mutations"]], margin = 2))
#reorder data in accordance with iCLuster
CLL_data <- CLL_data[c("Drugs","mRNA", "Methylation", "Mutations")]

# Center the data
CLL_data[["Drugs"]] <- scale(CLL_data[["Drugs"]], center = TRUE)
CLL_data[["mRNA"]] <- scale(CLL_data[["mRNA"]], center = TRUE)
CLL_data[["Methylation"]] <- scale(CLL_data[["Methylation"]], center = TRUE)
```

# iCluster
Run  on server with each run approx. 5 days on the server with 12 nodes.
```{r, eval =FALSE}
# Options
ncpus = 12
slurmidx <- as.numeric(Sys.getenv('SLURM_ARRAY_TASK_ID'))-1
k <- slurmidx %% 20 + 1
trial <- (slurmidx -1) %/% 20 +1

print(k)
print(trial)

# iCluster model selection with grid search 
doParallel::registerDoParallel(cores=ncpus)
tuned.out <- tune.iClusterPlus(
    cpus = ncpus, 
    dt1=CLL_data[["Drugs"]], dt2=CLL_data[["mRNA"]], dt3=CLL_data[["Methylation"]], dt4=CLL_data[["Mutations"]],
    type=c("gaussian","gaussian","gaussian","binomial"), K=k)
save(tuned.out, file=paste("iCluster.fit.k",k,"_",trial,".Rdata",sep=""))
```

```{r}
# load output from icluster
files <- list.files(datadir)
files <- files[grepl("iCluster.fit",files)]
output=alist()
for(i in 1:length(files)){
   load(file.path(datadir,files[i]))
   output[[i]]=tuned.out
}

# model characteristics
 nLambda = nrow(output[[1]]$lambda)
 nfits = length(output)
 k = sapply(output, function(out) ncol(out$fit[[1]]$meanZ))
 BIC = getBIC(output)
 devR = getDevR(output)
 colnames(BIC) <- colnames(devR) <- paste("K=",k,"_",sapply(files, function(nm) strsplit(nm, "_|[.]")[[1]][4]),sep="")
 names(output) <- paste("K=",k,"_",sapply(files, function(nm) strsplit(nm, "_|[.]")[[1]][4]),sep="")
 
# Plot BIC for different fits   
minBICid <- apply(BIC,2,which.min)
arr_id <- cbind(minBICid, 1:nfits)
ggplot(data.frame(K=k,BIC=BIC[arr_id]), aes(x=K, y=BIC)) +geom_point()

bestRunsForK <- sapply(1:20, function(ktmp) {
  arr_id_K <- cbind(minBICid[grepl(paste0("K=",ktmp,"_"),colnames(BIC))],
                    grep(paste0("K=",ktmp,"_"),colnames(BIC)))
  bestrun <- arr_id_K[which.min(BIC[arr_id_K]),2]
})
  
```
Best models are obtained for larger K.

# Turn to MOFA
```{r}
source("~/Documents/MOFA/CLL_MOFA_data/Analysis/code4manuscript/iCluster/iClustertoMOFA.R")
MOFAobjects <- lapply(output, function(f) iClustertoMOFA(f,data =CLL_data))
```

# Compare across different runs for the same K
```{r}
# for(k in 1:20){
for(k in c(10)){
Klist <- MOFAobjects[sapply(MOFAobjects, function(m) m@Dimensions$K==k)]
if(length(Klist)>0)
compareModels(Klist)
}
```

# Variance explained for best run with K=10
```{r}
plotVarianceExplained(MOFAobjects[[bestRunsForK[[10]]]], views=c("Drugs","mRNA", "Methylation"))
```

# Factor correlation for best run with K=10
```{r}
plotFactorCor(MOFAobjects[[bestRunsForK[[10]]]])
```

