---
title: "MOFA - comparison to iCluster"
author: "Britta Velten"
date: "21 August 2017"
output:
  BiocStyle::html_document:
    toc: true
---

```{r, warning=F, message=F}
setwd("/Users/bvelten/Documents/MOFA/CLL_MOFA_data/Analysis/clustering/")
devtools::load_all("/Users/bvelten/Documents/MOFA/MOFApackage/scGFA/MOFAtools/")
library(dplyr)
library(reshape2)
library(pheatmap)
library(ggplot2)
library(glmnet)
library(survival)
library(cowplot)
```

# MOFA model
```{r}
modelDir <- "~/Documents/MOFA/CLL_MOFA_data/out/common4iCluster/"
modelFiles <- list.files(modelDir)
MOFAmodels <- lapply(modelFiles, function(modelnm) loadModel(file.path(modelDir, modelnm), sortFactors = T))
# MOFAmodels <- lapply(MOFAmodels, function(model) {
#   factorNames(model) <- paste(factorNames(model), "MOFA", sep="_")
#   model})
names(MOFAmodels) <- sapply(modelFiles, function(nm) sub(".hdf5","",strsplit( nm,"_")[[1]][2]))

ZMOFA <- lapply(MOFAmodels, function(model) {
  Z <- getExpectations(model, "Z", "E")
  Z[,-1]
  })
names(ZMOFA) <- names(MOFAmodels) 

weightsMOFA <- lapply(MOFAmodels, function(model) {
 getExpectations(model, "SW", "E")
  })
names(weightsMOFA) <- names(MOFAmodels) 

```

# Data
```{r}
load("dataCLL.RData")
data <- data[c("meth", "mRNA", "viab")]
sapply(data,dim)
load("~/Documents/MOFA/CLL_MOFA_data/pace/data/patmeta.RData")
```

# iCluster
Run using iCluster/iClusterPlus_CLL.R on server with 185 values of lambda, each run approx. 5h on the server with 12 nodes.
```{r}
library(iClusterPlus)

# load output from icluster
files <- list.files("iCluster_CLL_out/")
files <- files[grepl("iclustertuned.out",files)]
output=alist()
for(i in 1:length(files)){
   load(file.path("iCluster_CLL_out",files[i]))
   output[[i]]=tuned.out
}

# model characteristics
 nLambda = nrow(output[[1]]$lambda)
 nK = length(output)
 k = sapply(output, function(out) ncol(out$fit[[1]]$meanZ))
 BIC = getBIC(output)
 devR = getDevR(output)
 colnames(BIC) <- colnames(devR) <- paste("K=",k,sep="")
 names(output) <-paste("K=",k,sep="")

 # Extract best fit for each k     
minBICid <- apply(BIC,2,which.min)
devRatMinBIC <- rep(NA,nK)
bestFit <- list()
for(i in 1:nK){
   devRatMinBIC[i] = devR[minBICid[i],i]
   bestFit[[i]] <- output[[i]]$fit[[minBICid[i]]]
}
names(bestFit) <- paste("K=",k,sep="")

# nice names
  for(i in 1:nK){
  colnames(bestFit[[i]]$meanZ) <- 1:ncol(bestFit[[i]]$meanZ) #paste(1:ncol(bestFit[[i]]$meanZ), "iCluster", sep="_")
  names(bestFit[[i]]$beta) <- c("mRNA", "meth", "viab")
  for (nm in names(bestFit[[i]]$beta)) {
    rownames(bestFit[[i]]$beta[[nm]]) <- colnames(data[[nm]])
    colnames(bestFit[[i]]$beta[[nm]]) <- 1:ncol(bestFit[[i]]$meanZ)# paste(1:ncol(bestFit[[i]]$meanZ), "iCluster", sep="_")
  }
  rownames(bestFit[[i]]$meanZ) <- rownames(data[[1]])
  names(bestFit[[i]]$alpha) <- names(bestFit[[i]]$beta)
  }

#reorder data in accordance with iCLuster
data <- data[names(bestFit[[1]]$beta)]
```

```{r}
# get factors and weights for R2 calculations  
ZiClust <- lapply(c(5,10,15,20), function(k) bestFit[[paste0("K=",k)]]$meanZ)
names(ZiClust) <- paste0("k",c(5,10,15,20))

weightsiClust <- lapply(c(5,10,15,20), function(k) bestFit[[paste0("K=",k)]]$beta)
names(weightsiClust) <- paste0("k",c(5,10,15,20))

interceptiClust <- lapply(c(5,10,15,20), function(k) bestFit[[paste0("K=",k)]]$alpha)
names(interceptiClust) <- paste0("k",c(5,10,15,20))

weightsPlusInterceptiClust <- lapply(c(5,10,15,20), function(k) {
  W <- lapply(seq_along(weightsiClust[[paste0("k",k)]]), function(d) cbind(intercept=interceptiClust[[paste0("k",k)]][[d]], weightsiClust[[paste0("k",k)]][[d]]))
  names(W) <- names(weightsiClust[[paste0("k",k)]])
  for(dt in names(W)) colnames(W[[dt]]) <- c("intercept",colnames(weightsiClust[[paste0("k",k)]][[dt]]))
  W
})
names(weightsPlusInterceptiClust) <- names(weightsiClust)
```


# Correlation
```{r corrplots, fig.path="fig/", dev=c("pdf", "png")}
for(k in c(5,10,15)){
  corrplot::corrplot(cor(ZMOFA[[paste0("k",k)]]))
  corrplot::corrplot(cor(ZiClust[[paste0("k",k)]]))
  corrplot::corrplot(cor(ZiClust[[paste0("k",k)]], ZMOFA[[paste0("k",k)]]))
}
```


#Variance Explained plot

```{r, echo=F}
calculateVarianceExplained4iClust <- function(Z,SW, Y, alpha, plotit=T, perFeature=F, 
                                       orderFactorsbyR2=F, showtotalR2=T, showVarComp=F) {
  
  K <- ncol(Z)
  views <-names(SW)
  factors <- colnames(Z)
  
  # Calculate predictions under the  MOFA model using all or a single factor
  Ypred_m <- lapply(views, function(m) Z%*%t(SW[[m]])); names(Ypred_m) <- views
  Ypred_mk <- lapply(views, function(m) {
                      ltmp <- lapply(factors, function(k) Z[,k]%*%t(SW[[m]][,k]) )
                      names(ltmp) <- factors
                      ltmp
                    })
  names(Ypred_mk) <- views

  # Calculate prediction under the null model (intercept only)
    #by default the null model is using the intercept LF if present and not the actual mean
    NullModel <- lapply(views, function(m)  Ypred_mk[[m]][[1]][1,] )
    names(NullModel) <- views
    resNullModel <- lapply(views, function(m) sweep(Y[[m]],2,NullModel[[m]],"-"))
    partialresNull <- lapply(views, function(m) sweep(Ypred_m[[m]],2,NullModel[[m]],"-"))
    names(resNullModel) <- views
    names(partialresNull) <- views
    
  # Remove intercept factor if present
  factorsNonconst <- factors[-1]
    
  # Calculate coefficient of determination
    # per view
    fvar_m <- sapply(views, function(m) 1 - sum((Y[[m]]-Ypred_m[[m]])**2, na.rm=T) / sum(resNullModel[[m]]**2, na.rm=T))
     
    # per view and feature
    if (perFeature)
      fvar_md <- lapply(views, function(m) 1 - colSums((Y[[m]]-Ypred_m[[m]])**2,na.rm=T) / colSums(resNullModel[[m]]**2,na.rm=T))
    
    # per factor and view
     if (showtotalR2) {
       fvar_mk <- sapply(views, function(m) sapply(factorsNonconst, function(k) 1 - sum((resNullModel[[m]]-Ypred_mk[[m]][[k]])**2, na.rm=T) / sum(resNullModel[[m]]**2, na.rm=T) ))
     } else {
       fvar_mk <- sapply(views, function(m) sapply(factorsNonconst, function(k) 1 - sum((partialresNull[[m]]-Ypred_mk[[m]][[k]])**2, na.rm=T) / sum(partialresNull[[m]]**2, na.rm=T) ))
     }
    
    # per factor and view and feature
    if (perFeature)
      fvar_mdk <- lapply(views, function(m) lapply(factorsNonconst, function(k) 1 - colSums((resNullModel[[m]]-Ypred_mk[[m]][[k]])**2,na.rm=T) / colSums(resNullModel[[m]]**2,na.rm=T)))
    
    # Set names
    names(fvar_m) <- views
    if(perFeature){
      names(fvar_md) <- views
      names(fvar_mdk) <- views
      for(i in names(fvar_md)) names(fvar_md[[i]]) <- colnames(Y[[i]])
      for(i in names(fvar_mdk)) rownames(fvar_mdk[[i]]) <- colnames(Y[[i]])
    }
    colnames(fvar_mk) <- views
    rownames(fvar_mk) <- factorsNonconst 
    
  
    if (plotit) {
      
      # Sort factors
      fvar_mk_df <- reshape2::melt(fvar_mk, varnames=c("factor","view"))
      fvar_mk_df$factor <- factor(fvar_mk_df$factor)
      hc <- hclust(dist(t(fvar_mk)))
      fvar_mk_df$view <- factor(fvar_mk_df$view, levels = colnames(fvar_mk)[hc$order])
      if(orderFactorsbyR2) factor_order <- order(rowSums(fvar_mk), decreasing = F) else factor_order <- rev(1:length(factorsNonconst))
      fvar_mk_df$factor <- factor(fvar_mk_df$factor, levels = factorsNonconst[factor_order])
      
      # Plot 1: grid with the variance explained per factor in each view
      hm <- ggplot(fvar_mk_df, aes(view,factor)) + 
        geom_tile(aes(fill=value), color="black") +
        guides(fill=guide_colorbar("R2")) +
        scale_fill_gradientn(colors=c("gray97","darkblue"), guide="colorbar") +
        ylab("Latent factor") +
        theme(
          # plot.margin = margin(5,5,5,5),
          plot.title = element_text(size=17, hjust=0.5),
          axis.title.x = element_blank(),
          axis.text.x = element_text(size=11, angle=60, hjust=1, vjust=1, color="black"),
          axis.text.y = element_text(size=12, color="black"),
          axis.title.y = element_text(size=15),
          axis.line = element_blank(),
          axis.ticks =  element_blank(),
          panel.background = element_blank()
          )
      
      hm <- hm + ggtitle("Variance explained per factor")  + 
      if (showtotalR2) {
        guides(fill=guide_colorbar("R2"))
      } else {
        guides(fill=guide_colorbar("Residual R2")) 
      }
        
      # Plot 2: barplot with coefficient of determination (R2) per view
      fvar_m_df <- data.frame(view=names(fvar_m), R2=fvar_m)
      fvar_m_df$view <- factor(fvar_m_df$view, levels = colnames(fvar_mk)[hc$order])
      
      bplt <- ggplot( fvar_m_df, aes(x=view, y=R2)) + 
        ggtitle("Total variance explained per view") +
        geom_bar(stat="identity", fill="deepskyblue4", width=0.9) +
        xlab("") + ylab("R2") +
        scale_y_continuous(expand=c(0.01,0.01), breaks = c(0,0.1,0.2,0.3)) +
        theme(
          plot.margin = unit(c(1,2.4,0,0), "cm"),
          panel.background = element_blank(),
          plot.title = element_text(size=17, hjust=0.5),
          axis.ticks.x = element_blank(),
          # axis.text.x = element_text(angle = 90, hjust = 1, vjust=0.5)
          axis.text.x = element_blank(),
          axis.text.y = element_text(size=12, color="black"),
          axis.title.y = element_text(size=13, color="black"),
          axis.line = element_line(size=rel(1.0), color="black")
            )
      
      # Join the two plots
      # Need to fix alignment using e.g. gtable...
      # gg_R2 <- gridExtra::arrangeGrob(hm, bplt, ncol=1, heights=c(length(factorsNonconst),7) )
      # gg_R2 <- gridExtra::arrangeGrob(bplt, hm, ncol=1, heights=c(1/2,1/2) )
      # gridExtra::grid.arrange(gg_R2)
      p <- plot_grid(bplt, hm, align="v", nrow=2, rel_heights=c(1/3,2/3))
      print(p)
     
      #optional: barplots with individual contributions of factors to explaining variance in a view, takes a lot of time....
      if (showVarComp){
        #Calculate 'variance component'/contribution of each factor
        cols  <- c(RColorBrewer::brewer.pal(9, "Set1"),RColorBrewer::brewer.pal(8, "Dark2"))
        varcomp_mk <- sapply(views, function(m) sapply(factorsNonconst, function(l) sum(sapply(factorsNonconst, function(k) cov(Ypred_mk[[m]][[l]], Ypred_mk[[m]][[k]])))))
        par(mfrow=c(1,2))
        barplot(t(t(varcomp_mk)/colSums(varcomp_mk)), col = cols, horiz = T, main = "Variance components per view", ncol = 2)
        plot.new()
        legend("center", fill=cols, legend=factorsNonconst)
      }
    }
    
  # Store results
    R2_list <- list(
      R2Total = fvar_m,
      R2PerFactor = fvar_mk)
    if(perFeature){
      R2_list$R2PerFactorAndFeature = fvar_mdk
      R2_list$R2PerFeature = fvar_md
    }
  
  return(R2_list)
 
}
```

```{r R2_plots, fig.path="fig/", dev=c("pdf", "png")}
data_scaled <- lapply(data, scale, center=T, scale=F)
for(k in c(5,10,15)){
  calculateVarianceExplained4iClust(cbind(intercept=1,ZiClust[[paste0("k",k)]]),
                                  weightsPlusInterceptiClust[[paste0("k",k)]],
                                  data_scaled, orderFactorsbyR2 = T)
  calculateVarianceExplained(MOFAmodels[[paste0("k",k)]], orderFactorsbyR2 = T)
}
```




