---
title: "MOFA Simulations: analysis of poisson likelihood"
output:
  BiocStyle::html_document:
    toc: true
---

```{r}
devtools::load_all("/Users/ricard/mofa/MOFAtools")
library(MOFAtools)
library(data.table)
library(purrr)
library(ggplot2)
```

```{r}
theme_fn <- function() {
    theme(
    # plot.title = element_text(size=titlesize),
    plot.margin = margin(10,10,10,10),
    axis.title.x=element_text(colour="black",size=rel(1.75), margin=margin(20,0,3,0)),
    axis.title.y=element_text(colour="black",size=rel(1.75), margin=margin(0,20,0,3)),
    axis.text.x=element_text(colour="black",size=rel(1.5)),
    axis.text.y=element_text(colour="black",size=rel(1.5)),
    axis.ticks.x = element_line(colour="black"),
    axis.ticks.y = element_line(colour="black"),
    axis.line.x = element_line(color="black"),
    axis.line.y = element_line(color="black"),
    legend.position="none",
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank()
  )
}
```

<!-- Load poisson and gaussian models trained on count data -->
```{r}

in.folder <- "/Users/ricard/data/MOFA/simulations/10Aug/results/nongaussian/poisson"

# Load poisson models
files <- list.files(in.folder, pattern="^poisson")
poisson_models <- list()
for (i in 1:length(files)) {
  split <- strsplit(files[i],"_")[[1]]
  likelihood <- split[1]
  trial <- substr(split[[2]],1,nchar(split[[2]])-5)
  poisson_models[[paste(likelihood,trial,sep="_")]] <- loadModel(paste0(in.folder,"/",files[i]))
}
poisson_dt <- data.table(
  trial = as.numeric(sapply(strsplit(names(poisson_models),"_"),"[[",2)),
  elbo = sapply(poisson_models, function(x) tail(x@TrainStats$elbo,1) ),
  k = sapply(poisson_models, function(x) tail(x@TrainStats$activeK,1) ),
  likelihood="Poisson"
)

# Load gaussian models
files <- list.files(in.folder, pattern="^gaussian")
gaussian_models <- list()
for (i in 1:length(files)) {
  split <- strsplit(files[i],"_")[[1]]
  likelihood <- split[1]
  trial <- substr(split[[2]],1,nchar(split[[2]])-5)
  gaussian_models[[paste(likelihood,trial,sep="_")]] <- loadModel(paste0(in.folder,"/",files[i]))
}
gaussian_dt <- data.table(
  trial = as.numeric(sapply(strsplit(names(gaussian_models),"_"),"[[",2)),
  elbo = sapply(gaussian_models, function(x) tail(x@TrainStats$elbo,1) ),
  k = sapply(gaussian_models, function(x) tail(x@TrainStats$activeK,1) ),
  likelihood="Gaussian"
)

# Concatenate
dt <- rbind(poisson_dt,gaussian_dt) %>% 
  .[,k:=k-1] %>%  # To account for the constant covariate that learns the mean
  .[,likelihood:=factor(likelihood, levels=c("Poisson","Gaussian"))]

```

<!-- Compare Evidence lower bound -->
```{r}
p1 <- ggplot(dt, aes(x=likelihood, y=-log(-elbo))) +
  geom_boxplot(aes(fill=likelihood), alpha=0.5, outlier.shape=NA) +
  ggbeeswarm::geom_quasirandom(aes(color=likelihood)) +
  labs(x="", y="Log Evidence lower bound") +
  theme_fn()
print(p1)

pdf("/Users/ricard/CLL/simulations/nongaussian/out/poisson/poisson_elbo.pdf", width=7, height=5, useDingbats = F)
print(p1)
dev.off()
```

<!-- Compare number of active factors -->
```{r}
p2 <- ggplot(dt, aes(x=likelihood, y=k)) +
  geom_bar(aes(group = trial, fill=likelihood), position = "dodge", stat="identity", color="black") +
  geom_hline(yintercept = 10, color="black", size=0.6, linetype="solid") +
  labs(x="", y="Number of infered factors") +
  scale_y_continuous(limits=c(0,13), breaks=c(5,10)) +
  theme_fn()
print(p2)

pdf("/Users/ricard/CLL/simulations/nongaussian/out/poisson/poisson_nfactors.pdf", width=7, height=5)
print(p2)
dev.off()
```

<!-- Compare reconstruction error -->

TO-DO: REPLACE THIS BY THE NEW PREDICT FUNCTION
```{r}
sigmoid <- function(x) 1/(1+exp(-x))

dt[,mse:=Inf]
for (i in 1:length(gaussian_models)) {
  Y <- getTrainData(gaussian_models[[i]], views="0")
  Z <- getFactors(gaussian_models[[i]], include_intercept = T)
  SW <- getWeights(gaussian_models[[i]], views="0")
  Ypred_gaussian <- t(Z %*% t(SW))
  mse_gaussian <- mean((Ypred_gaussian - Y)**2)
  dt[likelihood=="Gaussian" & trial==i-1, mse:=mse_gaussian]
}
for (i in 1:length(poisson_models)) {
  Y <- getTrainData(poisson_models[[i]], views="0")
  Z <- getFactors(poisson_models[[i]], include_intercept = T)
  SW <- getWeights(poisson_models[[i]], views="0")
  Ypred_poisson <- log(1 + exp(t(Z %*% t(SW))))
  mse_poisson <- mean((Ypred_poisson - Y)**2)
  dt[likelihood=="Poisson" & trial==i-1, mse:=mse_poisson]
}
dt[,likelihood:=factor(likelihood, levels=c("Poisson","Gaussian"))]

# Plot reconstruction error
p3 <- ggplot(dt, aes(x=likelihood, y=mse)) +
  geom_boxplot(aes(fill=likelihood), alpha=0.5, outlier.shape=NA) +
  ggbeeswarm::geom_quasirandom(aes(color=likelihood)) +
  labs(x="", y="Mean Squared Error") +
  theme_fn()
print(p3)

pdf("/Users/ricard/CLL/simulations/nongaussian/out/poisson/poisson_mse.pdf", width=7, height=5, useDingbats = F)
print(p3)
dev.off()
```

<!-- Compare distributions of reconstructed data -->
```{r}

dt_truth <- getTrainData(poisson_models[[1]])[["0"]] %>% as.data.table %>% melt() %>% .[,likelihood:="Truth"]

Z <- getFactors(poisson_models[[1]], include_intercept = T)
SW <- getWeights(poisson_models[[1]], views="0")
dt_poisson <- log(1 + exp(t(Z %*% t(SW)))) %>% as.data.table %>% melt() %>% .[,likelihood:="Poisson"]

Z <- getFactors(gaussian_models[[1]], include_intercept = T)
SW <- getWeights(gaussian_models[[1]], views="0")
dt_gaussian <- t(Z %*% t(SW)) %>% as.data.table %>% melt() %>% .[,likelihood:="Gaussian"]

dt <- rbind(dt_gaussian, dt_poisson)
dt[,likelihood:=factor(likelihood, levels=c("Poisson","Gaussian"))]

p4 <- ggplot(dt, aes(x=value, group=likelihood, fill=likelihood)) +
  geom_histogram(aes(y=..density..), alpha=0.75, binwidth=0.2) +
  xlim(c(-3,7)) +
  labs(x="", y="Density") +
  theme_bw() +
  theme(
    axis.title.x=element_text(colour="black",size=rel(2.0)),
    axis.title.y=element_text(colour="black",size=rel(2.0)),
    axis.text.x=element_text(colour="black",size=rel(1.5)),
    axis.text.y=element_text(colour="black",size=rel(1.5)),
    axis.ticks.x = element_line(colour="black"),
    axis.ticks.y = element_line(colour="black"),
    legend.position="top",
    legend.key = element_rect(fill='white'),
    legend.text = element_text(size=rel(1.25)),
    legend.title = element_text(size=rel(1.5))
  )
print(p4)

pdf("/Users/ricard/CLL/simulations/nongaussian/out/poisson/poisson_dist.pdf", width=6, height=4)
print(p4)
dev.off()
```

<!-- <!-- Joint plot --> -->
<!-- ```{r} -->

<!-- p <- cowplot::plot_grid(plotlist = list(p1,p2,p3,p4), ncol = 2, nrow = 2) -->
<!-- print(p) -->

<!-- pdf("/Users/ricard/CLL/simulations/nongaussian/out/poisson/poisson_all.pdf", width=6, height=4) -->
<!-- print(p) -->
<!-- dev.off() -->
<!-- ``` -->
