---
title: "Analysis of Factor 4"
author: "Britta Velten"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output:
  BiocStyle::html_document:
    toc: true
---
# Introduction
This script analyses Factor 4, which is linked to immune pathwyas and possible T-cell contamination. The analysis is based on the model and other objects defined in import_models.Rmd.

```{r, message=F, warning=F}
library(MOFAtools)
library(dplyr)
library(reshape2)
library(pheatmap)
library(survival)
library(gridExtra)
library(ggpubr)
library(ggplot2)
library(GGally)
library(magrittr)
library(Hmisc)
library(cowplot)
library(tidyverse)
library(beeswarm)
```

# I/O options
```{r}
#output path for plots and data
plotdir <- "figures/Factor4/"
if(!dir.exists(plotdir)) dir.create(plotdir)
knitr::opts_chunk$set(fig.path=plotdir, dev=c("png", "pdf"))
outdir <- "out"
```

# Get fitted model and related data
(Prepared in import_models.Rmd)
```{r}
# load model selected in import_models.Rmd
load(file.path(outdir,"out_import.RData"))

# helper function for some plots
source("plotting_utils.R")
```

# R2
```{r R2}
r2 <- calculateVarianceExplained(model)

r2df <- melt(r2$R2PerFactor[4,, drop=F], varnames = c("Factor", "Omic"))
r2df$Factor <- as.factor(r2df$Factor )
r2df$value <- pmax(r2df$value,0)
gg_r2 <- ggplot(r2df, aes(x=Omic, y=value, group=Factor, fill=Factor)) +geom_bar(stat="identity", position = "dodge") +ylab("R2")+ scale_fill_manual(values=c("3"="darkgreen", "4"="navy")) +xlab("") + geom_hline(yintercept=0.01, linetype="dashed", col="grey")
print(gg_r2)
```


# GSEA
```{r}
# use ensIDs
if(!all(grepl("ENS", MOFAtools::featureNames(model)$mRNA))) {
    symbols <- MOFAtools::featureNames(model)$mRNA
    MOFAtools::featureNames(model)$mRNA <- mRNA$ens_id[match(MOFAtools::featureNames(model)$mRNA, mRNA$symbol)]
}
```

```{r gsea}
data("reactomeGS")
gsea.out <- FeatureSetEnrichmentAnalysis(model, "mRNA", reactomeGS,
                                         statistical.test = "parametric",
                                         alpha = 0.01,min.size = 15)
names(gsea.out$sigPathways) <- colnames(Z)[-1]
df <- as.data.frame(gsea.out$pval.adj[,4])
colnames(df) <- c("LF_4")
df$pathway <- rownames(df)
rownames(df) <- NULL
df_sig <-filter(df, LF_4<0.001)
df_sig$pathway <- factor(df_sig$pathway, levels=df_sig$pathway[order(df_sig$LF_4, decreasing = T)])
df_sig <- filter(df_sig, pathway %in% tail(levels(df_sig$pathway),10))
gg_gsea <- ggplot(df_sig, aes(x=pathway, y=-log(LF_4))) + geom_point(position=position_dodge(.5)) +
  geom_linerange(aes(ymin=0,ymax=-log(LF_4)), linetype = "dashed",position=position_dodge(.5))+
  geom_hline(yintercept = -log10(0.01), linetype = "longdash") + 
  coord_flip() + ylab("-log p-value") + 
  scale_x_discrete(position = "top") +
  theme(plot.margin=margin(t=0,r=0,b=0,l=0.5,"cm"))+
  xlab("")
gg_gsea
```

```{r}
MOFAtools::featureNames(model)$mRNA <-symbols
```

# Heatmap
```{r heatmap}
getTopWeights <- function(model, view, factor, n=20){
  rownames(getWeights(model, view,factor)[[1]])[order(abs(getWeights(model, view, factor)[[1]]), decreasing = T)][1:n]
}
topWeights_mRNA_4 <- getTopWeights(model, "mRNA", "4", 10)

anno_df <- data.frame("Factor 4"=Z[,"4"])
mRNA_4_hm <- plotDataHeatmap(model, "mRNA", 4, transpose = T,
                                features= topWeights_mRNA_4,
                                sortSamples = T, 
                                annotation_col=anno_df, cluster_cols=F,
                                cluster_rows=TRUE,
                                treeheight_row = 0,
                                show_colnames=F)$gtable
gg_mRNA_4_hm <- as_ggplot(mRNA_4_hm)+theme(plot.margin=margin(t=0,r=-2,b=0,l=0.5,"cm"))
```

# Scatterplots
```{r CDs}
df <- data.frame(CD8A =  model@TrainData$mRNA["CD8A",],
                 CD8B =  model@TrainData$mRNA["CD8B",],
                 CD3D =  model@TrainData$mRNA["CD3D",],
                 CD300E = model@TrainData$mRNA["CD300E",],
                 LF4= Z[,"4"])
df <- gather(df, value=value, key=gene, -LF4)
df_cor <- group_by(df, gene) %>% dplyr::summarize(cor=round(cor(LF4,value, use="complete.obs"),2),
                                                  xpos = quantile(value, 0.8,na.rm=T))
gg_cds <- ggplot(df, aes(x= value, y= LF4)) +geom_point()+
 facet_wrap(~gene, scales="free_x", nrow=1) + geom_smooth(method="lm")+
  geom_text(data = df_cor, aes(x = xpos, y = 0.5, label = paste("cor=",cor)), col="blue")+
  xlab("Normalized expression") + ylab("Factor 4")

```

#Arrange plot
```{r Factor4_SXX, fig.width=10, fig.height=8}
plot_grid(gg_gsea, gg_mRNA_4_hm, gg_cds, ncol=1, labels=letters[1:3], align="hv", axis="l", label_size = 24)
```

# SessionInfo
```{r}
sessionInfo()
```
