---
title: "MOFA: Assessment of model robustness across multiple trials"
output:
  BiocStyle::html_document:
    toc: true
---

```{r}
devtools::load_all("/Users/ricard/mofa/MOFAtools")
library(MOFAtools)
library(data.table)
library(purrr)
library(ggplot2)
```

```{r}
theme_fn <- function() {
    theme(
    # plot.title = element_text(size=titlesize),
    plot.margin = margin(10,10,10,10),
    axis.title.x=element_text(colour="black",size=rel(1.75), margin=margin(20,0,3,0)),
    axis.title.y=element_text(colour="black",size=rel(1.75), margin=margin(0,20,0,3)),
    axis.text.x=element_text(colour="black",size=rel(1.5)),
    axis.text.y=element_text(colour="black",size=rel(1.5)),
    axis.ticks.x = element_line(colour="black"),
    axis.ticks.y = element_line(colour="black"),
    axis.line.x = element_line(color="black"),
    axis.line.y = element_line(color="black"),
    legend.position="none",
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank()
  )
}
```

<!-- Load trained models -->
```{r}
in.folder <- "/Users/ricard/data/CLL/out/test_final/17Aug"
files <- list.files(in.folder, pattern=".hdf5$")

models <- list()
for (file in files) {
  i = as.numeric(gsub("model","", strsplit(file,"\\.")[[1]][1]))
  models[[i]] <- loadModel(paste0(in.folder,"/",files[i]))
}
```

<!-- Compare Evidence Lower bound -->
```{r}
elbo_dt <- sapply(models, function(x) x@TrainStats$elbo) %>% as.data.table
# colnames(elbo_dt) <- paste0("model",1:length(models))
colnames(elbo_dt) <- as.character(1:length(models))
elbo_dt[,iteration:=1:nrow(elbo_dt)]

elbo_dt <- elbo_dt %>% melt(id.vars="iteration", variable.name="model", value.name="elbo")

ggplot(elbo_dt[iteration>=1], aes(x=iteration, y=elbo, group=model)) +
  geom_line(aes(color=model)) +
  labs(x="Iteartion", y="Evidence Lower Bound") +
  theme_fn()

# ggplot(elbo_dt[iteration==3000], aes(x=iteration, y=elbo, group=model)) +
#   geom_line(aes(color=model)) +
#   labs(x="Iteration", y="Evidence Lower Bound") +
#   theme_fn()

# tmp <- elbo_dt %>% split(.$model) %>% map(~ tail(.,n=1)) %>% rbindlist
# elbo_dt[elbo==max(tmp$elbo),model]
```


<!-- Compare Likelihoods -->
<!-- ```{r} -->
<!-- lik_dt <- sapply(models, function(x) x@TrainStats$elbo_terms[,"Y"]) %>% as.data.table -->
<!-- colnames(lik_dt) <- paste0("model",1:length(models)) -->
<!-- lik_dt[,iteration:=1:nrow(lik_dt)] -->

<!-- lik_dt <- lik_dt %>% melt(id.vars="iteration", variable.name="model", value.name="lik") -->

<!-- ggplot(lik_dt[iteration>=1], aes(x=iteration, y=lik, group=model)) + -->
<!--   geom_line(aes(color=model)) + -->
<!--   labs(x="Iteartion", y="Likelihood") + -->
<!--   theme_fn() -->

<!-- ggplot(lik_dt[iteration>=10], aes(x=iteration, y=lik, group=model)) + -->
<!--   geom_line(aes(color=model)) + -->
<!--   labs(x="Iteartion", y="Likelihood") + -->
<!--   theme_fn() -->
<!-- ``` -->

<!-- Compare infered number of latent variables -->
```{r}

## Training curve ##

lv_dt <- sapply(models, function(x) x@TrainStats$activeK) %>% as.data.table
# colnames(lv_dt) <- paste0("model",1:length(models))
colnames(lv_dt) <- as.character(1:length(models))
lv_dt[,iteration:=1:nrow(lv_dt)]
lv_dt <- lv_dt %>% melt(id.vars="iteration", variable.name="model", value.name="k") %>%
  .[complete.cases(k)] %>% .[,k:=k-1] # Remove the learnMean covariate

# Line plot
p <- ggplot(lv_dt, aes(x=iteration, y=k, group=model)) +
  # geom_line(aes(color=model), position=position_dodge(width=0.1)) +
  # geom_line(aes(color=model), position=position_jitter(w=0.0, h=0.1)) +
  geom_line(aes(color=model)) +
  scale_y_continuous(limits=c(0,25)) +
  scale_x_continuous(limits=c(0,1500)) +
  labs(x="Iteration", y="Number of active factors") +
  theme_fn()
print(p)

# pdf("/Users/ricard/CLL/robustness_across_trials/out/activeK.pdf", width=6, height=4.5)
# print(p)
# dev.off()


## Final number of latent variables ##

tmp <- lv_dt %>% split(.$model) %>% map(~ tail(.,n=1)) %>% rbindlist %>%
  merge(elbo_dt[iteration==max(elbo_dt$iteration)], by=c("iteration","model")) 
  # setorder(-k) %>% .[,model:=factor(model,levels=model)]

p <- ggplot(tmp, aes(x=model, y=k)) +
  geom_bar(aes(fill=elbo), stat="identity") +
  # geom_bar(stat="identity") +
  scale_y_continuous(breaks = c(0,5,10), expand=c(0,0.2)) +
  # scale_fill_gradient(low="red3",high="green3") +
  labs(x="", y="Number of active factors") +
  theme_bw() +
  # guides(fill=FALSE) +
  theme(
    # plot.title = element_text(size=titlesize),
    plot.margin = margin(10,10,10,10),
    axis.title.x=element_text(colour="black",size=rel(1.75), margin=margin(20,0,3,0)),
    axis.title.y=element_text(colour="black",size=rel(1.75), margin=margin(0,20,0,3)),
    # axis.text.x=element_text(colour="black",size=rel(1.5), angle=90),
    axis.text.x=element_blank(),
    axis.text.y=element_text(colour="black",size=rel(1.5)),
    axis.ticks.x = element_line(colour="black"),
    axis.ticks.y = element_line(colour="black"),
    axis.line.x = element_line(color="black"),
    axis.line.y = element_line(color="black"),
    legend.position="right",
    panel.grid.minor = element_blank(),
    panel.background = element_blank()
  )
print(p)

# pdf("/Users/ricard/MOFA_CLL/robustness/out/nfactors.pdf", width=7, height=5)
# print(p)
# dev.off()

```

<!-- Robustness of weights -->
```{r}
weights <- lapply(1:length(models), function(i) {
  model <- models[[i]]
  Wtmp <- getWeights(model, views="mRNA", factors="all")[[1]]
  colnames(Wtmp) <- paste(paste0("LF", 1:(ncol(Wtmp))), paste("model", i, sep=""), sep="_")
  Wtmp
  })

corWeights <- abs(cor(Reduce(cbind,weights)))
# pdf("/Users/ricard/MOFA_CLL/robustness/out/robustness_weights.pdf", width=7, height=5)
pheatmap::pheatmap(corWeights, show_rownames = F, show_colnames = F, 
                   color = colorRampPalette(c("white",RColorBrewer::brewer.pal(9,name="YlOrRd")))(100))
# dev.off()
```

<!-- Robustness of factors -->
```{r}
pdf("/Users/ricard/CLL/robustness_across_trials/out/robustness_factors.pdf", width=7, height=5)
compareModels(models, show_colnames=F, annotation_legend=F)
dev.off()
```
