---
title: "MOFA and CLL: downsampling analysis "
author: "Ricard Argelaguet"
date: "`r Sys.Date()`"
output:
  BiocStyle::html_document:
    toc: true
---

```{r}
devtools::load_all("/Users/ricard/mofa/MOFAtools")
library(MOFAtools)
library(data.table)
library(purrr)
library(ggplot2)
```

```{r}
theme_fn <- function() {
    theme(
    # plot.title = element_text(size=titlesize),
    plot.margin = margin(10,10,10,10),
    axis.title.x=element_text(colour="black",size=rel(1.75), margin=margin(20,0,3,0)),
    axis.title.y=element_text(colour="black",size=rel(1.75), margin=margin(0,20,0,3)),
    axis.text.x=element_text(colour="black",size=rel(1.5)),
    axis.text.y=element_text(colour="black",size=rel(1.5)),
    axis.ticks.x = element_line(colour="black"),
    axis.ticks.y = element_line(colour="black"),
    axis.line.x = element_line(color="black"),
    axis.line.y = element_line(color="black"),
    legend.position="none",
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank()
  )
}
```

<!-- Load downsampling models -->
```{r}

in.folder <- "/Users/ricard/data/CLL/out/downsample/results/mRNA"

# Incomplete data set
files <- list.files(in.folder, pattern="learnK_all.*\\.hdf5$")
incomplete_models <- list()
for (i in 1:length(files)) {
  split <- strsplit(files[i],"_")[[1]]
  N <- split[2]
  trial <- substr(split[[3]],1,nchar(split[[3]])-5)
  incomplete_models[[paste(N,trial,sep="_")]] <- loadModel(paste0(in.folder,"/",files[i]))
}


# Complete data set
files <- list.files(in.folder, pattern="learnK_common.*\\.hdf5$")
complete_models <- list()
for (i in 1:length(files)) {
  split <- strsplit(files[i],"_")[[1]]
  N <- split[2]
  trial <- substr(split[[3]],1,nchar(split[[3]])-5)
  complete_models[[paste(N,trial,sep="_")]] <- loadModel(paste0(in.folder,"/",files[i]))
}


```


```{r}

nsamples_downsampled <- seq(5,100,5)
ntrials <- 10

tmp <- expand.grid(nsamples_downsampled,1:ntrials) %>% as.data.table %>% setnames(c("nsamples_downsampled","trial")) %>% 
.[,c("K_complete","K_incomplete"):=0]

for (n in nsamples_downsampled) {
  for (i in 1:ntrials) {
    
    complete_model_file <- paste0("/Users/ricard/data/CLL/out/downsample/results/mRNA/learnK_common_",n,"_",i,".hdf5")
    incomplete_model_file <- paste0("/Users/ricard/data/CLL/out/downsample/results/mRNA/learnK_all_",n,"_",i,".hdf5")
    
    if (file.exists(complete_model_file) & file.exists(incomplete_model_file)) {
      complete_model <- loadModel(complete_model_file)
      incomplete_model <- loadModel(incomplete_model_file)
      
      tmp[nsamples_downsampled==n & trial==i, K_complete:=complete_model@Dimensions$K]
      tmp[nsamples_downsampled==n & trial==i, K_incomplete:=incomplete_model@Dimensions$K]
    }

  }
}

tmp2 <- melt(tmp,  measure.vars=c("K_complete","K_incomplete"), variable.name="type", value.name="K") %>%
  .[,c("nsamples_downsampled","trial"):=list(as.factor(nsamples_downsampled),as.factor(trial))]

ggplot(tmp2[K>0], aes(x=nsamples_downsampled, y=K)) +
  stat_summary(aes(group=type, color=type), stat="summary", fun.y="mean", geom="line") +
  stat_summary(aes(group=type, color=type), stat="summary", fun.data="mean_se", geom="errorbar") +
  theme_bw()


```

<!-- Imputation of drug response -->
```{r}

nsamples_downsampled <- seq(1,100,2)
ntrials <- 5

tmp <- expand.grid(nsamples_downsampled,1:ntrials) %>% as.data.table %>% setnames(c("nsamples_downsampled","trial"))
tmp[,c("complete_mse","incomplete_mse"):=0]

for (n in nsamples_downsampled) {
  for (i in 1:ntrials) {
    
    complete_model_file <- paste0("/Users/ricard/data/CLL/out/downsample/results/mRNA/common_",n,"_",i,".hdf5")
    incomplete_model_file <- paste0("/Users/ricard/data/CLL/out/downsample/results/mRNA/all_",n,"_",i,".hdf5")
    
    if (file.exists(complete_model_file) & file.exists(incomplete_model_file)) {
      complete_model <- detectPassengers(loadModel(complete_model_file))
      incomplete_model <- detectPassengers(loadModel(incomplete_model_file))
      
      # Ground truth data
      samples <- intersect(sampleNames(complete_model), sampleNames(incomplete_model))
      Y <- getTrainData(complete_model, views="Drugs")
      
      # Complete imputation
      Z <- getFactors(complete_model, include_intercept = T)
      SW <- getWeights(complete_model, views="Drugs")
      Ypred_complete <- t(Z %*% t(SW))[,samples] 

      # Incomplete imputation
      Z <- getFactors(incomplete_model, include_intercept = T)
      SW <- getWeights(incomplete_model, views="Drugs")
      Ypred_incomplete <- t(Z %*% t(SW))[,samples]      
      
      tmp[nsamples_downsampled==n & trial==i, complete_mse:=mean((Ypred_complete - Y)**2)]
      tmp[nsamples_downsampled==n & trial==i, incomplete_mse:=mean((Ypred_incomplete - Y)**2)]
    }
    

  }
}

tmp2 <- melt(tmp,  measure.vars=c("complete_mse","incomplete_mse"), variable.name="type", value.name="MSE") %>%
  .[,c("nsamples_downsampled","trial"):=list(as.factor(nsamples_downsampled),as.factor(trial))] %>%
  .[MSE>0] %>% .[,n:=.N,by=c("nsamples_downsampled","type")] %>% .[n>=4]


ggplot(tmp2, aes(x=nsamples_downsampled, y=MSE)) +
  # geom_boxplot(aes(fill=type))
  stat_summary(aes(group=type, color=type), stat="summary", fun.y="mean", geom="line") +
  stat_summary(aes(group=type, color=type), stat="summary", fun.data="mean_se", geom="errorbar") +
  theme_bw()

```
