---
title: "MOFA and CLL: downsampling analysis "
author: "Ricard Argelaguet"
date: "`r Sys.Date()`"
output:
  BiocStyle::html_document:
    toc: true
---

```{r}
# devtools::load_all("/Users/ricard/mofa/MOFAtools")
devtools::load_all("/homes/ricard/mofa/MOFAtools")
library(data.table)
library(purrr)
library(ggplot2)
```

```{r}
theme_fn <- function() {
    theme(
    # plot.title = element_text(size=titlesize),
    plot.margin = margin(10,10,10,10),
    axis.title.x=element_text(colour="black",size=rel(1.75), margin=margin(20,0,3,0)),
    axis.title.y=element_text(colour="black",size=rel(1.75), margin=margin(0,20,0,3)),
    axis.text.x=element_text(colour="black",size=rel(1.5)),
    axis.text.y=element_text(colour="black",size=rel(1.5)),
    axis.ticks.x = element_line(colour="black"),
    axis.ticks.y = element_line(colour="black"),
    axis.line.x = element_line(color="black"),
    axis.line.y = element_line(color="black"),
    legend.position="none",
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank()
  )
}
```

```{r}
# in.folder <- "/Users/ricard/data/downsample/results/mRNA"
in.folder <- "/hps/nobackup/stegle/users/ricard/downsample/results/mRNA"

nsamples_downsampled <- seq(5,75,5)
ntrials <- 25

```

<!-- <!-- Load downsampling models --> -->
<!-- ```{r} -->


<!-- # Incomplete data set -->
<!-- files <- list.files(in.folder, pattern="all.*\\.hdf5$") -->
<!-- incomplete_models <- list() -->
<!-- for (i in 1:length(files)) { -->
<!--   split <- strsplit(files[i],"_")[[1]] -->
<!--   N <- split[2] -->
<!--   trial <- substr(split[[3]],1,nchar(split[[3]])-5) -->
<!--   incomplete_models[[paste(N,trial,sep="_")]] <- loadModel(paste0(in.folder,"/",files[i])) -->
<!-- } -->


<!-- # Complete data set -->
<!-- files <- list.files(in.folder, pattern="common.*\\.hdf5$") -->
<!-- complete_models <- list() -->
<!-- for (i in 1:length(files)) { -->
<!--   split <- strsplit(files[i],"_")[[1]] -->
<!--   N <- split[2] -->
<!--   trial <- substr(split[[3]],1,nchar(split[[3]])-5) -->
<!--   complete_models[[paste(N,trial,sep="_")]] <- loadModel(paste0(in.folder,"/",files[i])) -->
<!-- } -->
<!-- ``` -->

<!-- Number of enriched gene sets -->
```{r}

# ighv <- read.table("/Users/ricard/data/CLL/views/minView=2/mut.txt")[,"IGHV",drop=F]
# trisomy12 <- read.table("/Users/ricard/data/CLL/views/minView=2/mut.txt")[,"trisomy12",drop=F]

# reactome <- readRDS("/Users/ricard/data/reactome/v59/homo_sapiens/out/human_reactome.rds")
# tmp <- read.table("/Users/ricard/data/reactome/v59/homo_sapiens/AllPathways.txt", header=F, quote="", sep="\t", stringsAsFactors=F)[,c(1,2)]
reactome <- readRDS("/hps/nobackup/stegle/users/ricard/reactome/v59/homo_sapiens/out/human_reactome.rds")
tmp <- read.table("/hps/nobackup/stegle/users/ricard/reactome/v59/homo_sapiens/AllPathways.txt", header=F, quote="", sep="\t", stringsAsFactors=F)[,c(1,2)]

reactome_meta <- tmp[,2]; names(reactome_meta) <- tmp[,1]
rownames(reactome) <- stringr::str_replace_all(rownames(reactome), reactome_meta)

tmp <- expand.grid(nsamples_downsampled,1:ntrials) %>% as.data.table %>% setnames(c("nsamples_downsampled","trial"))
tmp[,c("complete_r_ighv","incomplete_r_ighv","complete_r_trisomy12","incomplete_r_trisomy12","complete_ngenesets","incomplete_ngenesets"):=0]

for (n in nsamples_downsampled) {
  for (i in 1:ntrials) {
    print(n)
    
    complete_model_file <- paste0(in.folder,"/common_",n,"_",i,".hdf5")
    incomplete_model_file <- paste0(in.folder,"/all_",n,"_",i,".hdf5")
    
    if (file.exists(complete_model_file) & file.exists(incomplete_model_file)) {
      complete_model <- loadModel(complete_model_file, sortFactors=F)
      incomplete_model <- loadModel(incomplete_model_file, sortFactors=F)
      
      # samples <- intersect(sampleNames(complete_model), sampleNames(incomplete_model))
      
      # IGHV,
      # r_complete <- max(abs(cor(getFactors(complete_model)[samples,],ighv[samples,], use="complete.obs")), na.rm=T)
      # r_incomplete <- max(abs(cor(getFactors(incomplete_model)[samples,],ighv[samples,], use="complete.obs")), na.rm=T)
      # tmp[nsamples_downsampled==n & trial==i, complete_r_ighv:=r_complete]
      # tmp[nsamples_downsampled==n & trial==i, incomplete_r_ighv:=r_incomplete]
      
      # Trisomy 12
      # r_complete <- max(abs(cor(getFactors(complete_model)[samples,],trisomy12[samples,], use="complete.obs")), na.rm=T)
      # r_incomplete <- max(abs(cor(getFactors(incomplete_model)[samples,],trisomy12[samples,], use="complete.obs")), na.rm=T)
      # tmp[nsamples_downsampled==n & trial==i, complete_r_trisomy12:=r_complete]
      # tmp[nsamples_downsampled==n & trial==i, incomplete_r_trisomy12:=r_incomplete]
      
      # Calculate number of enriched pathways in the mRNA view
      # Complete data set
      npathways_complete <- FeatureSetEnrichmentAnalysis(
          complete_model,
          view = "mRNA",
          factors = "all",
          feature.sets = reactome,
          local.statistic = "loading",
          transformation = "abs.value",
          global.statistic = "mean.diff",
          statistical.test = "parametric",
          min.size=15,
          alpha=0.05)$pval.adj
      # Incomplete data set
      npathways_incomplete <- FeatureSetEnrichmentAnalysis(
          model = incomplete_model,
          view = "mRNA",
          factors = "all",
          feature.sets = reactome,
          local.statistic = "loading",
          transformation = "abs.value",
          global.statistic = "mean.diff",
          statistical.test = "parametric",
          min.size=15,
          alpha=0.05)$pval.adj
      
      tmp[nsamples_downsampled==n & trial==i, complete_ngenesets:=sum(npathways_complete<0.1, na.rm=T)]
      tmp[nsamples_downsampled==n & trial==i, incomplete_ngenesets:=sum(npathways_incomplete<0.1, na.rm=T)]
    }
  }
}

# tmp2 <- melt(tmp,  measure.vars=c("complete_r_ighv","incomplete_r_ighv"), variable.name="type", value.name="R") %>%
#   .[,c("nsamples_downsampled","trial"):=list(as.factor(nsamples_downsampled),as.factor(trial))]
# ggplot(tmp2[R>0], aes(x=nsamples_downsampled, y=R)) +
#   # geom_boxplot(aes(fill=type))
#   stat_summary(aes(group=type, color=type), stat="summary", fun.y="mean", geom="line") +
#   stat_summary(aes(group=type, color=type), stat="summary", fun.data="mean_se", geom="errorbar") +
#   theme_bw()

# tmp2 <- melt(tmp,  measure.vars=c("complete_r_trisomy12","incomplete_r_trisomy12"), variable.name="type", value.name="R") %>%
#   .[,c("nsamples_downsampled","trial"):=list(as.factor(nsamples_downsampled),as.factor(trial))]
# ggplot(tmp2[R>0], aes(x=nsamples_downsampled, y=R)) +
#   # geom_boxplot(aes(fill=type))
#   stat_summary(aes(group=type, color=type), stat="summary", fun.y="mean", geom="line") +
#   stat_summary(aes(group=type, color=type), stat="summary", fun.data="mean_se", geom="errorbar") +
#   theme_bw()

tmp2 <- melt(tmp,  measure.vars=c("complete_ngenesets","incomplete_ngenesets"), variable.name="type", value.name="ngenesets") %>%
  .[,c("nsamples_downsampled","trial"):=list(nsamples_downsampled,as.factor(trial))] %>%
  .[,nsamples_downsampled:=as.numeric(nsamples_downsampled)/136]

p <- ggplot(tmp2[ngenesets>0], aes(x=nsamples_downsampled, y=ngenesets)) +
  stat_summary(aes(group=type, color=type), fun.y="mean", geom="line", size=1) +
  stat_summary(aes(group=type, color=type), fun.data="mean_se", geom="errorbar", width=0.01, alpha=0.6) +
  theme_bw() +
  # scale_x_continuous(breaks=c(0.1,0.2,0.3,0.4,0.5,0.6,0.7)) +
  labs(x="Downsampling fraction", y="Number of enriched gene sets") +
  scale_color_discrete(labels=c("Complete data set", "Incomplete data set")) +
  theme(
    axis.title= element_text(size=rel(1.7)),
    axis.text = element_text(color="black", size=rel(1.3)),
    legend.position = "top",
    legend.title = element_blank(),
    legend.text = element_text(size=rel(1.3))
  )
print(p)

# pdf("/Users/ricard/CLL/downsample/out/genesets.pdf", width = 7, height = 4.5)
pdf("/homes/ricard/CLL/downsample/out/genesets.pdf", width = 7, height = 4.5)
print(p)
dev.off()
```

<!-- Imputation of drug response -->
```{r}

# Load ground truth data
# Y <- read.table("/Users/ricard/data/CLL/views/minView=all/viab.txt", header=T) %>% as.matrix %>% t
Y <- read.table("/hps/nobackup/stegle/users/ricard/CLL/views/minView=2/viab.txt", header=T) %>% as.matrix

tmp <- expand.grid(nsamples_downsampled,1:ntrials) %>% as.data.table %>% setnames(c("nsamples_downsampled","trial"))
tmp[,c("complete_mse","incomplete_mse"):=0]

for (n in nsamples_downsampled) {
  print(n)
  for (i in 1:ntrials) {
    
    complete_model_file <- paste0(in.folder,"/imputation_common_",n,"_",i,".hdf5")
    incomplete_model_file <- paste0(in.folder,"/imputation_all_",n,"_",i,".hdf5")
    
    if (file.exists(complete_model_file) & file.exists(incomplete_model_file)) {
      complete_model <- loadModel(complete_model_file, sortFactors=F)
      incomplete_model <- loadModel(incomplete_model_file, sortFactors=F)
      
      # samples <- intersect(sampleNames(complete_model), sampleNames(incomplete_model))
      
      # Get missing ids
      Y_complete <- getTrainData(complete_model, views="Drugs")[[1]]
      # ids_complete <- which(is.na(Y_complete), arr.ind = T)
      Y_incomplete <- getTrainData(incomplete_model, views="Drugs")[[1]]
      # ids_incomplete <- which(is.na(Y_incomplete), arr.ind = T)
      
      samples <- apply(Y_complete,2, function(x) mean(is.na(x))) == 1
      
      # Calculate predictions in complete data
      # Z <- getFactors(complete_model, include_intercept = F)
      # SW <- getWeights(complete_model, views="Drugs")[[1]]
      # Ypred_complete <- t(Z %*% t(SW))[,samples] 
      complete_model <- imputeMissing(complete_model, views = "Drugs")
      Ypred_complete <- getImputedData(complete_model)[["Drugs"]]

      # Calculate predictions in incomplete data
      # Z <- getFactors(incomplete_model, include_intercept = F)
      # SW <- getWeights(incomplete_model, views="Drugs")[[1]]
      # Ypred_incomplete <- t(Z %*% t(SW))[,samples]      
      incomplete_model <- imputeMissing(incomplete_model, views = "Drugs")
      Ypred_incomplete <- getImputedData(incomplete_model)[["Drugs"]]
      
      # Compute mean squared error
      tmp[nsamples_downsampled==n & trial==i, complete_mse:=mean((Ypred_complete[,samples]-Y[,samples])**2, na.rm=T)]
      tmp[nsamples_downsampled==n & trial==i, incomplete_mse:=mean((Ypred_incomplete[,samples]-Y[,samples])**2, na.rm=T)]
    }
  }
}

tmp2 <- melt(tmp,  measure.vars=c("complete_mse","incomplete_mse"), variable.name="type", value.name="MSE") %>%
  .[,c("nsamples_downsampled","trial"):=list(nsamples_downsampled,as.factor(trial))] %>%
  .[MSE>0] %>% .[,nsamples_downsampled:=nsamples_downsampled/136]

p <- ggplot(tmp2, aes(x=nsamples_downsampled, y=MSE, group=type, color=type)) +
  stat_summary(fun.y="mean", geom="line", size=1) +
  stat_summary(fun.data="mean_se", geom="errorbar", width=0.01, alpha=0.6) +
  theme_bw() +
  labs(x="Downsampling fraction", y="Mean squared error") +
  scale_color_discrete(labels=c("Complete data set", "Incomplete data set")) +
  scale_x_continuous(breaks=c(0.1,0.2,0.3,0.4,0.5,0.6,0.7)) +
  theme(
    axis.title= element_text(size=rel(1.7)),
    axis.text = element_text(color="black", size=rel(1.3)),
    legend.position = "top",
    legend.title = element_blank(),
    legend.text = element_text(size=rel(1.3))
  )
# print(p)

pdf("/homes/ricard/CLL/downsample/out/imputation.pdf", width = 7, height = 4.5)
print(p)
dev.off()
```

<!-- Number of active latent variables -->
```{r}

tmp <- expand.grid(nsamples_downsampled,1:ntrials) %>% as.data.table %>% setnames(c("nsamples_downsampled","trial"))
tmp[,c("complete_k","incomplete_k"):=0]

for (n in nsamples_downsampled) {
  print(n)
  for (i in 1:ntrials) {
    
    complete_model_file <- paste0(in.folder,"/common_",n,"_",i,".hdf5")
    incomplete_model_file <- paste0(in.folder,"/all_",n,"_",i,".hdf5")
    
    if (file.exists(complete_model_file) & file.exists(incomplete_model_file)) {
      complete_model <- loadModel(complete_model_file, sortFactors = F)
      incomplete_model <- loadModel(incomplete_model_file, sortFactors = F)
      
      tmp[nsamples_downsampled==n & trial==i, complete_k:=getDimensions(complete_model)[["K"]]]
      tmp[nsamples_downsampled==n & trial==i, incomplete_k:=getDimensions(incomplete_model)[["K"]]]
    }
  }
}

tmp2 <- melt(tmp,  measure.vars=c("complete_k","incomplete_k"), variable.name="type", value.name="K") %>%
  .[,c("nsamples_downsampled","trial"):=list(nsamples_downsampled,as.factor(trial))] %>%
  .[K>0] %>% .[,nsamples_downsampled:=nsamples_downsampled/136]


p <- ggplot(tmp2, aes(x=nsamples_downsampled, y=K, group=type, color=type)) +
  stat_summary(fun.y="mean", geom="line", size=1) +
  stat_summary(fun.data="mean_se", geom="errorbar", width=0.01, alpha=0.6) +
  theme_bw() +
  labs(x="Downsampling fraction", y="Number of active factors") +
  scale_color_discrete(labels=c("Complete data set", "Incomplete data set")) +
  # scale_x_continuous(breaks=c(0.1,0.2,0.3,0.4,0.5,0.6,0.7)) +
  theme(
    axis.title= element_text(size=rel(1.7)),
    axis.text = element_text(color="black", size=rel(1.3)),
    legend.position = "top",
    legend.title = element_blank(),
    legend.text = element_text(size=rel(1.3))
  )
print(p)


# pdf("/Users/ricard/CLL/downsample/out/nfactors.pdf", width = 7, height = 4.5)
pdf("/homes/ricard/CLL/downsample/out/nfactors.pdf", width = 7, height = 4.5)
print(p)
dev.off()
```

<!-- Survival prediction -->
```{r}

# source("/Users/ricard/MOFA_CLL/downsampling/predictSurvival.R")
source("/homes/ricard/MOFA_CLL/downsampling/predictSurvival.R")

tmp <- expand.grid(nsamples_downsampled,1:ntrials) %>% as.data.table %>% setnames(c("nsamples_downsampled","trial"))
tmp[,c("complete_survival","incomplete_survival"):=0]

for (n in nsamples_downsampled) {
  print(n)
  for (i in 1:ntrials) {

    complete_model_file <- paste0(in.folder,"/common_",n,"_",i,".hdf5")
    incomplete_model_file <- paste0(in.folder,"/all_",n,"_",i,".hdf5")

    if (file.exists(complete_model_file) & file.exists(incomplete_model_file)) {
      complete_model <- loadModel(complete_model_file, sortFactors = F)
      incomplete_model <- loadModel(incomplete_model_file, sortFactors = F)
      tmp[nsamples_downsampled==n & trial==i, complete_survival:=predictSurvival(complete_model)[1] ]
      tmp[nsamples_downsampled==n & trial==i, incomplete_survival:=predictSurvival(incomplete_model)[1] ]
    }
  }
}

tmp2 <- melt(tmp,  measure.vars=c("complete_survival","incomplete_survival"), variable.name="type", value.name="survival_prediction") %>%
  .[,c("nsamples_downsampled","trial"):=list(nsamples_downsampled,as.factor(trial))] %>%
  .[survival_prediction>0] %>% .[,nsamples_downsampled:=nsamples_downsampled/136]


p <- ggplot(tmp2, aes(x=nsamples_downsampled, y=survival_prediction, group=type, color=type)) +
  stat_summary(fun.y="mean", geom="line", size=1) +
  stat_summary(fun.data="mean_se", geom="errorbar", width=0.01, alpha=0.6) +
  theme_bw() +
  labs(x="Downsampling fraction", y="Harrell's C-index") +
  scale_color_discrete(labels=c("Complete data set", "Incomplete data set")) +
  # scale_x_continuous(breaks=c(0.1,0.2,0.3,0.4,0.5,0.6,0.7)) +
  theme(
    axis.title= element_text(size=rel(1.7)),
    axis.text = element_text(color="black", size=rel(1.3)),
    legend.position = "top",
    legend.title = element_blank(),
    legend.text = element_text(size=rel(1.3))
  )
# print(p)


# pdf("/Users/ricard/CLL/downsample/out/imputation.pdf", width = 7, height = 4.5)
pdf("/homes/ricard/CLL/downsample/out/survival.pdf", width = 7, height = 4.5)
print(p)
dev.off()
```

