---
title: "Comparing iCluster, GFA and MOFA with non-gaussian simulated data"
---

The training data is generated using generate_data.py

```{r, warning=FALSE, message=FALSE}
devtools::load_all("/Users/ricard/mofa/MOFAtools")
# devtools::load_all("/homes/ricard/mofa/MOFAtools")
library(dplyr)
library(tidyr)
library(purrr)
library(data.table)
library(magrittr)
library(ggplot2)
library(GFA)
library(iClusterPlus)
```

```{r}
impute <- function(d, margin) {
  if (margin == 1)
    means <- rowMeans(d, na.rm=T)
  else if (margin == 2)
    means <- colMeans(d, na.rm=T)
  else
    stop("Margin has to be either 1 (rows) or 2 (cols)")
  
  if (any(is.na(means))) {
    stop('Insufficient data for mean imputation!')
  }
  
  for (i in 1:length(means)) {
    if (margin == 1)
      d[i,is.na(d[i,])] <- means[i]
    else if (margin == 2)
      d[is.na(d[,i]), i] <- means[i]
  }
  return (d)
}
```

<!-- Define I/O and options -->
```{r}

# I/O
io <- list()
io$in.data <- "/Users/ricard/data/MOFA_revision/simulations/joint/data/NOIDEA"
io$out <- "/Users/ricard/data/MOFA_revision/simulations/joint/results"

# io$in.data <- "/hps/nobackup/stegle/users/ricard/MOFA/simulations/data/nongaussian"
# io$out <- "/homes/ricard/mofa_rebuttal/gfa_comparison/simulations/out"

# Options
opts <- list()
opts$trials <- as.character(0:9)  # trials (to be generated by generate_data.py)
```

<!-- Load simulated data and create MOFA object -->
```{r}
data <- list()
data_norm <- list()
data_imputed <- list()
data_filt <- list()
data_norm_filt <- list()
data_imputed_filt <- list()
for (i in opts$trials) {

  # Each trial is a separate data set
  gaussian_view <- read.table(sprintf("%s/trial%s_0.txt",io$in.data, i)) %>% as.matrix
  bernoulli_view <- read.table(sprintf("%s/trial%s_1.txt",io$in.data, i)) %>% as.matrix
  poisson_view <- read.table(sprintf("%s/trial%s_2.txt",io$in.data, i)) %>% as.matrix
  data[[i]] <- list(gaussian_view,bernoulli_view,poisson_view)
  names(data[[i]]) <- c("gaussian","bernoulli","poisson")
  
  # Each trial is on the same data set under different random initialisations
  # j <- "0"
  # gaussian_view <- read.table(sprintf("%s/trial%s_0.txt",io$in.data, j)) %>% as.matrix %>% t
  # bernoulli_view <- read.table(sprintf("%s/trial%s_1.txt",io$in.data, j)) %>% as.matrix %>% t
  # poisson_view <- read.table(sprintf("%s/trial%s_2.txt",io$in.data, j)) %>% as.matrix %>% t
  
  # Convert NaN to NA
  for (j in 1:length(data[[i]])) { data[[i]][[j]][is.nan(data[[i]][[j]])] <- NA }

  # Impute data before normalisation
  data_imputed[[i]][["gaussian"]] <- impute(data[[i]][["gaussian"]], margin = 2)
  data_imputed[[i]][["bernoulli"]] <- round(impute(data[[i]][["bernoulli"]], margin = 2))
  data_imputed[[i]][["poisson"]] <- round(impute(data[[i]][["poisson"]], margin = 2))
  
  # Normalize data
  data_norm[[i]] <- normalizeData(data[[i]], type="center")
  # data_norm[[i]] <- normalizeData(lapply(data[[i]],t), type="scaleOverall") # did this before

  # Remove features with no variance
  for (j in names(data[[i]])) {
    # Normalized data
  	variableFeatures <- apply(data_norm[[i]]$train[[j]],2,var,na.rm=T)>0
  	data_norm_filt[[i]][[j]] <- data_norm[[i]]$train[[j]][,variableFeatures]
  	# Unnormalized data
  	variableFeatures <- apply(data[[i]][[j]],2,var,na.rm=T)>0
  	data_filt[[i]][[j]] <- data[[i]][[j]][,variableFeatures]
  	# Unnormalized imputed data
  	variableFeatures <- apply(data_imputed[[i]][[j]],2,var)>0
  	data_imputed_filt[[i]][[j]] <- data_imputed[[i]][[j]][,variableFeatures]
  }
}
```

<!-- Train MOFA models -->
```{r}
DataOptions <- getDefaultDataOpts()
TrainOptions <- getDefaultTrainOpts()
TrainOptions$maxiter <- 2000
TrainOptions$tolerance <- 0.01
TrainOptions$learnFactors <- T
TrainOptions$DropFactorThreshold <- 0.03
  
mofa_models <- list()
# mofa_time <- list()
for (i in opts$trials) {
  mofa_models[[i]] <- list()
  trials.modelselection <- 3
  for (j in 1:trials.modelselection) {
    tmp <- createMOFAobject(map(data[[i]],t))
    
    DirOptions <- list("dataDir" = tempdir(), "outFile" = tempfile())
    
    ModelOptions <- getDefaultModelOpts(tmp)
    ModelOptions$numFactors <- 20
    ModelOptions$learnIntercept <- T
    ModelOptions$sparsity <- F
    
    # Prepare MOFA object for training
    tmp <- prepareMOFA(tmp, DataOptions = DataOptions, DirOptions = DirOptions,
                                   ModelOptions = ModelOptions, TrainOptions = TrainOptions)
    
    # Run MOFA
    # ptm <- proc.time()
    mofa_models[[i]][[j]] <- runMOFA(tmp, DirOptions, mofaPath="/Users/ricard/anaconda2/bin/mofa")
    # mofa_models[[i]] <- runMOFA(tmp, DirOptions, mofaPath="/nfs/software/stegle/users/ricard/conda-envs/py27/bin/mofa")
    # mofa_time[[i]] <- proc.time() - ptm
  }
  
  # Select the model with the best ELBO
  elbo <- sapply(mofa_models[[i]], function(x) tail(x@TrainStats$elbo,n=1))
  mofa_models[[i]] <- mofa_models[[i]][[which.max(elbo)]]
  
  # Save output
  # saveRDS(mofa_models[[i]], sprintf("%s/mofa_simulation_nongaussian_%s.rds",io$out,i))
}
```

<!-- Train GFA model -->
```{r}
gfa_opts <- getDefaultOpts()
# opts$tauGrouped <- FALSE
# opts$convergenceCheck <- TRUE
# gfa_opts$iter.burnin <- 1000
# gfa_opts$iter.max <- 3000
# gfa_opts <- informativeNoisePrior(data_norm[[i]]$train, gfa_opts, noiseProportion = 0.5, conf = 1)

gfa_models <- list()
gfa_time <- list()
for (i in opts$trials) {
  ptm <- proc.time()
  gfa_models[[i]] <- gfa(data_norm[[i]]$train, gfa_opts, K = 20)
  gfa_time[[i]] <- proc.time() - ptm
  saveRDS(gfa_models[[i]], sprintf("%s/gfa_simulation_nongaussian_%s.rds",io$out,i))
}

```

<!-- Train iCluster model -->
Not implemented here, use run_icluster.R and run_icluster.sh



<!-- Load pre-trained MOFA models -->
```{r}
# MOFA
mofa_models <- map(opts$trials, ~ readRDS(sprintf("%s/mofa_simulation_nongaussian_%s.rds",io$out,.)))
names(mofa_models) <- opts$trials
```

<!-- Load pre-trained GFA models -->
```{r}
gfa_models <- map(opts$trials, ~ readRDS(sprintf("%s/gfa_simulation_nongaussian_%s.rds",io$out,.)))
names(gfa_models) <- opts$trials
```

<!-- Load pre-trained iCluster models, do model selection, and conver to MOFAobjects -->
```{r}
opts$icluster.nfactors <- 20

icluster.out <- list()
for (trial in opts$trials) {
  print(trial)
  icluster.out[[trial]] <- list()
  for (k in as.character(1:opts$icluster.nfactors)) {
    file <- paste0(io$out,"/icluster_simulation_nongaussian_",trial,"_",k,".RData")
    if (file.exists(file)) {
      load(file)
      icluster.out[[trial]][[k]] <- tuned.out
    }
  }
  
  if (length(icluster.out[[trial]]) > 0) {
    # Model selection for 'lambda' using BIC
    kvec = as.character(sapply(icluster.out[[trial]], function(out) ncol(out$fit[[1]]$meanZ)))
    bic <-  getBIC(icluster.out[[trial]])
    bestFitIdx <- apply(bic,2,which.min)
    names(bestFitIdx) <- kvec
    icluster.out[[trial]] <- lapply(kvec, function(j) icluster.out[[trial]][[j]]$fit[[bestFitIdx[j]]])
    names(icluster.out[[trial]]) <-kvec
    
    # Model selection for 'K' using BIC
    bic <- sapply(icluster.out[[trial]],"[[","BIC")
    icluster.out[[trial]] <- icluster.out[[trial]][[which.min(bic)]]
  }
}
```

<!-- Create a MOFA object from GFA results -->
```{r}
gfa_mofamodels <- list()
for (i in opts$trials) {
  
  # Parse W
  D <- sapply(map(data_norm[[i]]$train,t),nrow)
  M <- length(data[[i]])
  tmp <- rep(NA,sum(D))
  for (m in 1:M) {
    if (m==1) {
      tmp[1:D[m]] <- m
    } else {
      tmp[(cumsum(D)[m-1]+1):cumsum(D)[m]] <- m
    }
  }
  W <- gfa_models[[i]]$W
  W <- cbind(W,tmp)
  
  W_split <- lapply( split( W[,1:ncol(W)-1], W[,ncol(W)] ), matrix, ncol=ncol(W)-1)
  names(W_split) <- names(data[[i]])
  
  # Parse Alpha
  Alpha_split <- split(gfa_models[[i]]$Z, row(gfa_models[[i]]$Z))
  names(Alpha_split) <- names(data[[i]])
  
  # Create a MOFA object
  gfa_mofamodels[[i]] <- createMOFAobject(map(data_norm[[i]]$train,t))
  gfa_mofamodels[[i]]@ModelOpts$learnIntercept <- F
  gfa_mofamodels[[i]]@TrainData <- map(data_norm[[i]]$train,t)
  gfa_mofamodels[[i]]@Expectations <- list(
    "Y"=data_norm[[i]]$train,
    "Z"=gfa_models[[i]]$X,
    "W"=W_split,
    "Alpha"=Alpha_split
  )
  gfa_mofamodels[[i]]@Dimensions[["K"]] <- ncol(gfa_models[[i]]$X)
  viewNames(gfa_mofamodels[[i]]) <- names(data[[i]])
  sampleNames(gfa_mofamodels[[i]]) <- as.character(1:nrow(data[[i]][[1]]))
  factorNames(gfa_mofamodels[[i]]) <- as.character(1:ncol(gfa_models[[i]]$X))
  gfa_mofamodels[[i]]@Status <- "trained"
  gfa_mofamodels[[i]]@ModelOpts$likelihood <- c("gaussian","gaussian","gaussian")
  names(gfa_mofamodels[[i]]@ModelOpts$likelihood) <- c("gaussian","bernoulli","poisson")
  
  # Sort factors by variance explained
  r2 <- rowSums(calculateVarianceExplained(gfa_mofamodels[[i]])$R2PerFactor)
  order_factors <- c(names(r2)[order(r2, decreasing = T)])
  gfa_mofamodels[[i]] <- subsetFactors(gfa_mofamodels[[i]],order_factors)
  factorNames(gfa_mofamodels[[i]]) <- as.character(1:ncol(gfa_models[[i]]$X))
}
```

<!-- Create a MOFA object from iCluster results -->
```{r}
icluster_mofamodels <- list()
for (trial in opts$trials[-1]) {
  # tmp <- lapply(data_filt[[trial]],t)
  tmp <- list(
    gaussian=data_norm_filt[[trial]][["gaussian"]],
    bernoulli=data_imputed_filt[[trial]][["bernoulli"]],
    poisson=data_imputed_filt[[trial]][["poisson"]]
  )
  model <- icluster.out[[trial]]

  # Z
  Z <- model$meanZ
  Z <- cbind(intercept=1,Z)
  colnames(Z) <- c("intercept",1:ncol(model$meanZ))
  rownames(Z) <- as.character(1:nrow(data_filt[[trial]][[1]]))
  
  W <- model$beta
  for (i in 1:length(tmp)) { 
    rownames(W[[i]]) <- rownames(tmp[[i]])  
    colnames(W[[i]]) <- as.character(1:ncol(model$meanZ))
  }
  intercept <- model$alpha
  W <- lapply(seq_along(W), function(d) cbind(intercept=intercept[[d]], W[[d]])) 
  names(W) <- names(tmp)

  icluster_mofamodels[[trial]] <- createMOFAobject(lapply(tmp,t))
  icluster_mofamodels[[trial]]@ModelOpts$learnIntercept <- T
  icluster_mofamodels[[trial]]@TrainData <- lapply(tmp,t)
  icluster_mofamodels[[trial]]@Expectations <- list("Y"=tmp, "Z"=Z, "W"=W)
  icluster_mofamodels[[trial]]@Dimensions[["K"]] <- ncol(model$meanZ)    
  
  viewNames(icluster_mofamodels[[trial]]) <- names(tmp)
  sampleNames(icluster_mofamodels[[trial]]) <- as.character(1:nrow(data_filt[[trial]][[1]]))
  # factorNames(icluster_mofamodels[[trial]]) <- c("intercept",as.character(1:ncol(model$meanZ)))
  # mofa_object@Dimensions <- list(K=k, M=m, N=n, D=d)

  icluster_mofamodels[[trial]]@Status <- "trained"
  icluster_mofamodels[[trial]]@ModelOpts$likelihood <- c("gaussian","bernoulli","poisson")
  names(icluster_mofamodels[[trial]]@ModelOpts$likelihood) <- names(tmp)
}
```

<!-- Plot running time differences -->
```{r}
# df_time <- data.frame(
#   GFA=unlist(map(gfa_time,3)),
#   MOFA=unlist(map(mofa_time,3))
# ) %>% gather(key="model", value="time")
# 
# p <- ggplot(df_time, aes(x=model, y=time)) +
#   labs(x="", y="Time (s)") +
#   geom_boxplot(aes(color=model)) +
#   ggbeeswarm::geom_quasirandom(aes(color=model)) +
#   theme_bw() +
#   theme(
#     axis.title.x = element_blank(),
#     axis.title.y = element_text(colour="black", size=20, vjust=1.5),
#     axis.text.x = element_text(colour="black",size=rel(1.7), margin=margin(5,0,0,0)),
#     axis.text.y = element_text(colour="black",size=rel(1.7)),
#     axis.line = element_line(colour="black", size=rel(0.5)),
#     axis.ticks.x = element_line(colour="black", size=rel(1.0)),
#     axis.ticks.y = element_line(colour="black", size=rel(1.0)),
#     legend.position="none"
#   )
# print(p)
```


<!-- Number of active factors -->
```{r}

df <- rbind(
  data.frame(model="GFA", trial=as.factor(1:length(gfa_mofamodels)), k=sapply(gfa_mofamodels, function(x) ncol(getFactors(x)))),
  data.frame(model="iCluster", trial=as.factor(1:length(icluster_mofamodels)), k=sapply(icluster_mofamodels, function(x) ncol(getFactors(x, include_intercept = F)))),
  data.frame(model="MOFA", trial=as.factor(1:length(mofa_models)), k=sapply(mofa_models, function(x) ncol(getFactors(x, include_intercept = F))))
)
df$model <- factor(df$model, labels = c("GFA","iCluster","MOFA"))

p <- ggplot(df, aes(x=model, y=k, fill=model, group=trial)) +
  geom_bar(stat="identity", position = "dodge", width=0.5, color="black") +
  coord_cartesian(ylim=c(0,25)) +
  scale_y_continuous(breaks = c(0,5,10,15,20,25), expand=c(0,0.1)) +
  # scale_x_discrete(expand=c(0,0 ))
  geom_hline(yintercept = 20, linetype = "dashed") +
  geom_hline(yintercept = 10, linetype = "solid") +
  labs(x="", y="Optimal number of factors") +
  theme_bw() +
  theme(
    # plot.title = element_text(size=titlesize),
    plot.margin = margin(10,10,10,10),
    axis.title.x=element_text(colour="black",size=rel(1.75), margin=margin(20,0,3,0)),
    axis.title.y=element_text(colour="black",size=rel(1.75), margin=margin(0,20,0,3)),
    axis.text.x=element_text(colour="black",size=rel(1.5), angle=90),
    # axis.text.x=element_blank(),
    axis.text.y=element_text(colour="black",size=rel(1.7)),
    axis.ticks.x = element_line(colour="black"),
    axis.ticks.y = element_line(colour="black"),
    axis.line.x = element_line(color="black"),
    axis.line.y = element_line(color="black"),
    legend.position="none",
    panel.grid.minor = element_blank(),
    panel.background = element_blank()
  )
print(p)

pdf(file=paste0(io$out,"/pdf/summarized/activeFactors.pdf"), height=5, width=4.5)
print(p)
dev.off()
```

<!-- Subset the first 10 factors -->
```{r}
mofa_models_small <- map(mofa_models, function(x) if ((getDimensions(x)[["K"]]-1)>10) { subsetFactors(x, factors=1:10) } else { x })
gfa_mofamodels_small <- map(gfa_mofamodels, function(x) if ((getDimensions(x)[["K"]]-1)>10) { subsetFactors(x, factors=1:10) } else { x })
icluster_mofamodels_small <- map(icluster_mofamodels, function(x) if ((getDimensions(x)[["K"]]-1)>10) { subsetFactors(x, factors=1:10) } else { x })
```


<!-- Total variance explained -->

MOFA
```{r}
r2_total_mofa <- list()
for (i in opts$trials) {
  # plotVarianceExplained(mofa_models[[1]], include_intercept=T)
  r2 <- calculateVarianceExplained(mofa_models[[i]], include_intercept=T)
  r2_total_mofa[[i]] <- data.frame(trial=i, model="mofa", likelihood=names(r2$R2Total), r2=r2$R2Total)
} 
r2_total_mofa <- do.call("rbind",r2_total_mofa)
```

GFA
```{r}
r2_total_gfa <- list()
for (i in opts$trials) {
  # plotVarianceExplained(mofa_models[[1]], include_intercept=T)
  r2 <- calculateVarianceExplained(gfa_mofamodels[[i]], include_intercept=T)
  r2_total_gfa[[i]] <- data.frame(trial=i, model="gfa", likelihood=names(r2$R2Total), r2=r2$R2Total)
}
r2_total_gfa <- do.call("rbind",r2_total_gfa)
```

iCluster can't compute R2 in non-gaussian views
```{r}

```

```{r}
r2_total <- rbind(r2_total_mofa,r2_total_gfa) %>% group_by(likelihood,model) %>% 
  summarise(meanr2=mean(r2), lower=mean(r2)-sd(r2), upper=mean(r2)+sd(r2))

p <- ggplot(r2_total, aes(x=model, y=meanr2)) +
  labs(x="", y="Total Variance explained (R2)") +
  # geom_boxplot(aes(fill=model)) +
  geom_bar(aes(fill=model), stat="identity", color="black") +
  geom_errorbar(aes(x=model, ymin=lower, ymax=upper), width = 0.20) +
  # ggbeeswarm::geom_quasirandom(aes(color=model)) +
  theme_bw() +
  # coord_cartesian(ylim=c(0.5,1.0)) +
  facet_wrap(~likelihood, scales = "fixed") +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_text(colour="black", size=15, vjust=1.5),
    axis.text.x = element_blank(),
    axis.text.y = element_text(colour="black",size=rel(1.7)),
    axis.line = element_line(colour="black", size=rel(0.5)),
    axis.ticks.x = element_line(colour="black", size=rel(1.0)),
    axis.ticks.y = element_line(colour="black", size=rel(1.0)),
    legend.position="top"
  )
print(p)
```


<!-- Variance explained per factor -->

```{r}
mofa_r2 <- map(mofa_models, ~ calculateVarianceExplained(., cluster=F))
gfa_r2 <- map(gfa_mofamodels, ~ calculateVarianceExplained(., cluster=F))

# mofa_factorR2 <- map(mofa_r2, ~ .[["R2PerFactor"]] %>% apply(.,1, function(x) mean(x[x>0])) %>% as.data.table %>% .[,factor:=1:.N] ) %>% rbindlist() %>% setnames(".","r2") %>% .[,trial:=1:.N, by="factor"] %>% .[,model:="mofa"]
mofa_factorR2 <- map(mofa_r2, ~ .[["R2PerFactor"]] %>% apply(.,1, mean) %>% as.data.table %>% .[,factor:=1:.N] ) %>% rbindlist() %>% setnames(".","r2") %>% .[,trial:=1:.N, by="factor"] %>% .[,model:="mofa"]

# gfa_factorR2 <- map(gfa_r2, ~ .[["R2PerFactor"]] %>% apply(.,1, function(x) mean(x[x>0])) %>% as.data.table %>% .[,factor:=1:.N] ) %>% rbindlist() %>% setnames(".","r2") %>% .[,trial:=1:.N, by="factor"] %>% .[,model:="gfa"]
gfa_factorR2 <- map(gfa_r2, ~ .[["R2PerFactor"]] %>% apply(.,1, mean) %>% as.data.table %>% .[,factor:=1:.N] ) %>% rbindlist() %>% setnames(".","r2") %>% .[,trial:=1:.N, by="factor"] %>% .[,model:="gfa"]

df_factorR2 <- rbind(mofa_factorR2, gfa_factorR2) %>% 
  .[,.(mean_r2=mean(r2), sd_r2=sd(r2)),by=c("factor","model")] 

order_factors <- mofa_factorR2[,mean(r2),by="factor"] %>% setkey %>% .$factor

p <- ggplot(df_factorR2, aes(x=as.factor(factor), y=mean_r2, group=model)) +
  labs(x="", y="Variance explained (R2)") +
  geom_bar(aes(fill=model), stat="identity", color="black", position="dodge", width=0.75) +
  # geom_errorbar(aes(ymin=mean_r2-sd_r2, ymax=mean_r2+sd_r2), width=.25, position=position_dodge(.9)) +
  # coord_cartesian(expand=c(0,0), ylim=c(0,0.45)) +
  # geom_hline(yintercept = 0.10, linetype = "dashed") +
  theme_bw() +
  # facet_wrap(~view, scales="free") +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_text(colour="black", size=20, vjust=1.5),
    axis.text.x = element_text(colour="black",size=rel(1.7), margin=margin(5,0,0,0)),
    axis.text.y = element_text(colour="black",size=rel(1.7)),
    axis.line = element_line(colour="black", size=rel(0.5)),
    axis.ticks.x = element_line(colour="black", size=rel(1.0)),
    axis.ticks.y = element_line(colour="black", size=rel(1.0)),
    legend.position="top"
  )
print(p)

pdf(file=paste0(io$out,"/pdf/summarized/R2perFactor.pdf"), height=5.5, width=6.8)
print(p)
dev.off()
```

MOFA
```{r}
for (i in opts$trials) {
  
  # Extract R2
  r2 <- calculateVarianceExplained(mofa_models[[i]])$R2PerFactor
  
  # Calculate total R2 per factor
  r2[r2<0] <- 0
  r2 <- sort(apply(r2,1,mean), decreasing = T)
  
  foo <- data.frame(
    factor=as.factor(1:length(r2)),
    r2=r2
  )
  
  # Plot  
  p <- ggplot(foo, aes(x=factor, y=r2)) +
    labs(x="Factor", y="Fraction of Variance explained (R2)") +
    geom_bar(stat="identity", color="grey") +
    # geom_hline(yintercept = 0.10, linetype = "dashed") +
    scale_y_continuous(expand=c(0,0.005), limits = c(0,0.20), breaks=seq(0.05,0.20,0.05)) +
    # scale_y_continuous(expand=c(0,0.005), breaks=seq(0,0.4,0.05)) +
    theme_bw() +
    theme(
      axis.title.x = element_text(colour="black", size=15),
      axis.title.y = element_text(colour="black", size=15),
      axis.text.x = element_text(colour="black",size=rel(0.8)),
      # axis.text.x = element_blank(),
      axis.text.y = element_text(colour="black",size=rel(1.5)),
      axis.line = element_line(colour="black", size=rel(0.5))
    )
  pdf(file=paste0(io$out,"/pdf/mofa_TotalVarExplained",i,".pdf"), height=4, width=5)
  print(p)
  dev.off()
}
```

GFA
```{r}
for (i in opts$trials) {
  
  # Extract R2
  r2 <- calculateVarianceExplained(gfa_mofamodels[[i]])$R2PerFactor
  
  # Calculate total R2 per factor
  r2[r2<0] <- 0
  r2 <- sort(apply(r2,1,mean), decreasing = T)
  
  foo <- data.frame(
    factor=as.factor(1:length(r2)),
    r2=r2
  )
  
  # Plot  
  p <- ggplot(foo, aes(x=factor, y=r2)) +
    labs(x="Factor", y="Fraction of Variance explained (R2)") +
    geom_bar(stat="identity", color="grey") +
    # geom_hline(yintercept = 0.10, linetype = "dashed") +
    scale_y_continuous(expand=c(0,0.005), limits = c(0,0.20), breaks=seq(0.05,0.20,0.05)) +
    theme_bw() +
    theme(
      axis.title.x = element_text(colour="black", size=15),
      axis.title.y = element_text(colour="black", size=15),
      axis.text.x = element_text(colour="black",size=rel(0.8)),
      # axis.text.x = element_blank(),
      axis.text.y = element_text(colour="black",size=rel(1.5)),
      axis.line = element_line(colour="black", size=rel(0.5))
    )
  pdf(file=paste0(io$out,"/pdf/gfa_TotalVarExplained",i,".pdf"), height=4, width=5)
  print(p)
  dev.off()
}
```

iCluster can't compute R2 in non-gaussian views
```{r}

```

<!-- Factor correlation -->

Across trials
```{r}
gfa_factorCor <- map(gfa_mofamodels, ~
  plotFactorCor(.) %>% as.data.table %>% .[,factor1:=1:.N] %>% melt(id.vars="factor1", variable.name="factor2", value.name = "r")
) %>% rbindlist %>% .[,trial:=1:.N, by=c("factor1","factor2")] %>% .[,model:="GFA"]

mofa_factorCor <- map(mofa_models, ~
  plotFactorCor(.) %>% as.data.table %>% .[,factor1:=1:.N] %>% melt(id.vars="factor1", variable.name="factor2", value.name = "r")
) %>% rbindlist %>% .[,trial:=1:.N, by=c("factor1","factor2")] %>% .[,model:="MOFA"]

icluster_factorCor <- map(icluster_mofamodels, ~
  plotFactorCor(.) %>% as.data.table %>% .[,factor1:=1:.N] %>% melt(id.vars="factor1", variable.name="factor2", value.name = "r")
) %>% rbindlist %>% .[,trial:=1:.N, by=c("factor1","factor2")] %>% .[,model:="iCluster"]


df_factorCor <- rbind(mofa_factorCor, gfa_factorCor, icluster_factorCor) %>%
  .[,c("factor1","factor2"):=list(as.numeric(factor1),as.numeric(factor2))] %>%
  .[factor1!=factor2] %>%
  .[,.(r=max(r)),by=c("factor1","model","trial")]
  # %>% .[,.(mean_r=mean(r), sd_r=sd(r)),by=c("factor","model")]

df_factorCor$model <- factor(df_factorCor$model, labels = c("GFA","iCluster","MOFA"))
# df_factorCor[model=="MOFA",factor1:=paste0("MOFA_",factor1)]
# df_factorCor[model=="GFA",factor1:=paste0("GFA_",factor1)]

# p <- ggplot(df_factorCor, aes(x=r, fill=model)) +
p <- ggplot(df_factorCor, aes(x=model, y=r, fill=model)) +
  # geom_density(alpha=0.5) +
  labs(x="", y="Correlation between factors") +
  geom_boxplot(outlier.shape = NA) +
  # geom_violin() +
  # geom_bar(aes(fill=model), stat="identity", color="black", position="dodge") +
  # geom_errorbar(aes(ymin=mean_r2-sd_r2, ymax=mean_r2+sd_r2), width=.25, position=position_dodge(.9)) +
  coord_cartesian(ylim=c(0.0,1.0)) +
  # coord_cartesian(ylim=c(0,0.7)) +
  # geom_hline(yintercept = 0.01, linetype = "dashed") +
  theme_bw() +
  # facet_wrap(~view, scales="free") +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_text(colour="black", size=20, vjust=1.5),
    axis.text.x = element_text(colour="black",size=rel(1.5), angle=90),
    axis.text.y = element_text(colour="black",size=rel(1.75)),
    axis.line = element_line(colour="black", size=rel(0.5)),
    axis.ticks.x = element_line(colour="black", size=rel(1.0)),
    axis.ticks.y = element_line(colour="black", size=rel(1.0)),
    legend.position="none"
  )
print(p)

pdf(file=paste0(io$out,"/pdf/summarized/FactorCor.pdf"), height=5, width=4.5)
print(p)
dev.off()
```

Formal statistical test
```{r}
# df_factorCor[,mean(r),by="model"]
# t.test(x=df_factorCor[model=="MOFA",r], y=df_factorCor[model=="GFA",r], var.equal=FALSE)[["p.value"]]
```

MOFA
```{r}
for (i in opts$trials) {
  pdf(file=paste0(io$out,"/pdf/mofa_corFactors",i,".pdf"), height=5.5, width=7, useDingbats = F)
  plotFactorCor(mofa_models[[i]])
  dev.off()
}

# r <- map(mofa_models, plotFactorCor)

# rr <- map(r,abs) %>% Reduce("+",.) / length(r)
# corrplot::corrplot(rr)
```

GFA
```{r}
for (i in opts$trials) {
  pdf(file=paste0(io$out,"/pdf/gfa_corFactors",i,".pdf"), height=5.5, width=7, useDingbats = F)
  plotFactorCor(gfa_mofamodels[[i]])
  dev.off()
}

# r <- map(gfa_mofamodels, plotFactorCor)
# rr <- map(r,abs) %>% Reduce("+",.) / length(r)
# corrplot::corrplot(rr)
```

iCluster
```{r}
for (i in opts$trials) {
  if (!is.null(icluster_mofamodels[[i]])) {
    pdf(file=paste0(io$out,"/pdf/icluster_corFactors",i,".pdf"), height=5.5, width=7, useDingbats = F)
    plotFactorCor(icluster_mofamodels[[i]])
    dev.off()
  }
}

# r <- map(gfa_mofamodels, plotFactorCor)
# rr <- map(r,abs) %>% Reduce("+",.) / length(r)
# corrplot::corrplot(rr)
```




<!-- Recovery of true factors -->

MOFA
```{r}
Z <- list()
r_sorted_mofa <- list()
for (i in opts$trials) {
  Z[[i]] <- read.table(sprintf("%s/trial%s_Z.txt",io$in.data,i)) %>% as.matrix
  
  Z_mofa <- getFactors(mofa_models[[i]], include_intercept = F)
  r <- abs(cor(Z_mofa,Z[[i]]))
  # corrplot::corrplot(r, tl.cex=0.1)
  
  # order_factors <- unname(apply(r,1,which.max))
  # Z_sorted <- Z[[i]][,order_factors]
  # 
  # r_sorted_mofa[[i]] <- abs(cor(Z_mofa,Z_sorted))
  # rownames(r_sorted_mofa[[i]]) <- paste0("MOFA_",1:nrow(r_sorted_mofa[[i]]))
  # colnames(r_sorted_mofa[[i]]) <- paste0("TRUE_",1:nrow(r_sorted_mofa[[i]]))
  # corrplot::corrplot(r_sorted_mofa[[i]])
  
  order_factors <- unique(unname(apply(r,2,which.max)))
  order_factors <- c(order_factors, setdiff(1:ncol(Z_mofa), order_factors))
  
  r_sorted_mofa[[i]] <- abs(cor(Z_mofa[,order_factors],Z[[i]]))
  # rownames(r_sorted_mofa[[i]]) <- paste0("MOFA_",1:nrow(r_sorted_mofa[[i]]))
  rownames(r_sorted_mofa[[i]]) <- paste0("LF_",order_factors)
  colnames(r_sorted_mofa[[i]]) <- paste0("TRUE_",1:ncol(r_sorted_mofa[[i]]))
  
  pdf(file=paste0(io$out,"/pdf/mofa_corTrueFactors",i,".pdf"))
  corrplot::corrplot(r_sorted_mofa[[i]], tl.col="black", tl.cex=0.75)
  dev.off()
}

# rr <- r_sorted_mofa %>% Reduce("+",.) / length(r_sorted_mofa)
# corrplot::corrplot(rr)

# pdf(file=paste0(io$out,"/activeFactors.pdf"), height=5.5, width=7)
# print(p)
# dev.off()
```

GFA
```{r}
Z <- list()
r_sorted_gfa <- list()
for (i in opts$trials) {
  Z[[i]] <- read.table(sprintf("%s/trial%s_Z.txt",io$in.data,i)) %>% as.matrix
  
  Z_gfa <- getFactors(gfa_mofamodels[[i]])
  r <- abs(cor(Z_gfa,Z[[i]]))
  # corrplot::corrplot(r, tl.cex=0.01)
  
  order_factors <- unique(unname(apply(r,2,which.max)))
  order_factors <- c(order_factors, setdiff(1:ncol(Z_gfa), order_factors))
  
  r_sorted_gfa[[i]] <- abs(cor(Z_gfa[,order_factors],Z[[i]]))
  # rownames(r_sorted_gfa[[i]]) <- paste0("GFA_",1:nrow(r_sorted_gfa[[i]]))
  rownames(r_sorted_gfa[[i]]) <- paste0("LF_",order_factors)
  colnames(r_sorted_gfa[[i]]) <- paste0("TRUE_",1:ncol(r_sorted_gfa[[i]]))
  
  pdf(file=paste0(io$out,"/pdf/gfa_corTrueFactors",i,".pdf"), useDingbats = F)
  corrplot::corrplot(r_sorted_gfa[[i]], tl.col="black", tl.cex=0.75)
  dev.off()
}
```

iCluster
```{r}

in.data <- "/Users/ricard/data/MOFA_revision/simulations/joint/data"

Z <- list()
r_sorted_icluster <- list()
for (i in opts$trials[-1]) {
  Z[[i]] <- read.table(sprintf("%s/trial%s_Z.txt",in.data,i)) %>% as.matrix
  
  Z_icluster <- getFactors(icluster_mofamodels[[i]], include_intercept = F)
  r <- abs(cor(Z_icluster,Z[[i]]))
  # corrplot::corrplot(r, tl.cex=0.01)
  
  order_factors <- unique(unname(apply(r,2,which.max)))
  order_factors <- c(order_factors, setdiff(1:ncol(Z_icluster), order_factors))
  
  r_sorted_icluster[[i]] <- abs(cor(Z_icluster[,order_factors],Z[[i]]))
  # rownames(r_sorted_icluster[[i]]) <- paste0("icluster_",1:nrow(r_sorted_icluster[[i]]))
  rownames(r_sorted_icluster[[i]]) <- paste0("LF_",order_factors)
  colnames(r_sorted_icluster[[i]]) <- paste0("TRUE_",1:ncol(r_sorted_icluster[[i]]))
  
  pdf(file=paste0(io$out,"/pdf/icluster_corTrueFactors",i,".pdf"), useDingbats = F)
  corrplot::corrplot(r_sorted_icluster[[i]], tl.col="black", tl.cex=0.75)
  dev.off()
}
```

```{r}
# Subset the top K factors with better correlation and plot correlation
gfa=map(r_sorted_gfa, function(x) tail(sort(apply(x,1,max)),n=10) %>% as.data.frame) %>% rbindlist %>% .[,model:="GFA"] %>% setnames(".","cor")
mofa=map(r_sorted_mofa, function(x) tail(sort(apply(x,1,max)),n=10) %>% as.data.frame) %>% rbindlist %>% .[,model:="MOFA"] %>% setnames(".","cor")
icluster=map(r_sorted_icluster, function(x) tail(sort(apply(x,1,max)),n=10) %>% as.data.frame) %>% rbindlist %>% .[,model:="iCluster"] %>% setnames(".","cor")

df_factorRecovery <- rbind(gfa,mofa,icluster)

p <- ggplot(df_factorRecovery, aes(x=model, y=cor, fill=model)) +
  # geom_density(alpha=0.5) +
  labs(x="", y="Correlation with true factors") +
  geom_boxplot(outlier.shape = NA) +
  # geom_violin() +
  # geom_bar(aes(fill=model), stat="identity", color="black", position="dodge") +
  # geom_errorbar(aes(ymin=mean_r2-sd_r2, ymax=mean_r2+sd_r2), width=.25, position=position_dodge(.9)) +
  # coord_cartesian(xlim=c(0,1.0)) +
  coord_cartesian(ylim=c(0.5,1.0)) +
  # geom_hline(yintercept = 0.01, linetype = "dashed") +
  theme_bw() +
  # facet_wrap(~view, scales="free") +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_text(colour="black", size=20, vjust=1.5),
    axis.text.x = element_text(colour="black",size=rel(1.5), angle=90),
    axis.text.y = element_text(colour="black",size=rel(1.5)),
    axis.line = element_line(colour="black", size=rel(0.5)),
    axis.ticks.x = element_line(colour="black", size=rel(1.0)),
    axis.ticks.y = element_line(colour="black", size=rel(1.0)),
    legend.position="none"
  )
print(p)

pdf(file=paste0(io$out,"/pdf/summarized/FactorCorTrue.pdf"), height=5, width=4.5)
print(p)
dev.off()
```

```{r}
# df_factorRecovery[,median(cor),by="model"]
# t.test(x=df_factorRecovery[model=="MOFA",cor], y=df_factorRecovery[model=="GFA",cor], var.equal=FALSE)[["p.value"]]
```


STOP HERE


<!-- (IGNORE) Compare variance decomposition pattern -->

GFA
```{r}
for (i in opts$trials) {
  
  # Load true pattern
  Z <- read.table(sprintf("/Users/ricard/data/MOFA/rebuttal/simulations/nongaussian/trial%s_Z.txt",i)) %>% as.matrix
  alpha <- read.table(sprintf("/Users/ricard/data/MOFA/rebuttal/simulations/nongaussian/trial%s_alpha.txt",i)) %>% as.matrix
  
  # Sort factors to match true pattern
  Z_gfa <- getFactors(gfa_mofamodels[[i]])
  r <- abs(cor(Z_gfa,Z))
  rownames(r) <- paste0("GFA_",1:nrow(r))
  colnames(r) <- paste0("TRUE_",1:nrow(r))
  # corrplot::corrplot(r)
  order_factors <- unname(apply(r,1,which.max))
  # tmp <- subsetFactors(gfa_mofamodels[[i]], order_factors)

  # Plot true pattern
  alpha_sorted <- alpha[,rev(order_factors)]
  pheatmap::pheatmap(t(alpha_sorted), color=c("darkblue","gray97"), show_rownames = F, legend = F, cluster_cols = F, cluster_rows = F)
    
  # Plot MOFA pattern
  plotVarianceExplained(gfa_mofamodels[[i]], cluster=F) %>% print
}
```

MOFA
```{r}
for (i in opts$trials) {
  
  # Load true pattern
  Z <- read.table(sprintf("/Users/ricard/data/MOFA/rebuttal/simulations/nongaussian/trial%s_Z.txt",i)) %>% as.matrix
  alpha <- read.table(sprintf("/Users/ricard/data/MOFA/rebuttal/simulations/nongaussian/trial%s_alpha.txt",i)) %>% as.matrix
  
  # Sort factors to match true pattern
  Z_mofa <- getFactors(mofa_models[[i]], include_intercept = F)
  r <- abs(cor(Z_mofa,Z))
  rownames(r) <- paste0("MOFA_",1:nrow(r))
  colnames(r) <- paste0("TRUE_",1:nrow(r))
  corrplot::corrplot(r)
  order_factors <- unname(apply(r,1,which.max))
  # tmp <- subsetFactors(mofa_models[[i]], c("intercept",order_factors))

  # Plot true pattern
  alpha_sorted <- alpha[,rev(order_factors)]
  pheatmap::pheatmap(t(alpha_sorted), color=c("darkblue","gray97"), show_rownames = F, legend = F, cluster_cols = F, cluster_rows = F)
    
  # Plot MOFA pattern
  plotVarianceExplained(mofa_models[[i]], cluster=F) %>% print
}
```




<!-- (IGNORE) Reconstruction error -->
```{r}
# gfa_mofamodels[[1]]@ModelOpts$likelihood <- c("gaussian","bernoulli","poisson")
# names(gfa_mofamodels[[1]]@ModelOpts$likelihood) <- c("gaussian","bernoulli","poisson")
tmp <- expand.grid(c("gaussian","bernoulli","poisson"),opts$trials) %>% 
  rename(likelihood=Var1) %>% rename(trial=Var2) %>% mutate(mofa=NA) %>% mutate(gfa=NA) %>% mutate(mean=NA)

for (i in opts$trials) {
  Ypred_mofa <- predict(mofa_models[[i]], type="response")
  Ypred_gfa <- predict(gfa_mofamodels[[i]], type="response")
  
  for (j in names(data[[1]])) {
    Ytrue <- mofa_models[[i]]@TrainData[[j]]
    tmp[tmp$likelihood==j & tmp$trial==i,"mofa"] <- mean((Ypred_mofa[[j]] - Ytrue)**2)
    Ytrue <- gfa_mofamodels[[i]]@TrainData[[j]]
    tmp[tmp$likelihood==j & tmp$trial==i,"gfa"] <- mean((Ypred_gfa[[j]] - Ytrue)**2)
  }
}

foo <- tmp %>% gather(key=model, value=error, -likelihood, -trial)

p <- ggplot(foo, aes(x=model, y=error, fill=model)) +
  labs(x="", y="Mean Squared Error") +
  geom_boxplot() +
  ggbeeswarm::geom_quasirandom(aes(color=model)) +
  theme_bw() +
  facet_wrap(~likelihood, scales = "free") +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_text(colour="black", size=20, vjust=1.5),
    axis.text.x = element_text(colour="black",size=rel(1.7), margin=margin(5,0,0,0)),
    axis.text.y = element_text(colour="black",size=rel(1.7)),
    axis.line = element_line(colour="black", size=rel(0.5)),
    axis.ticks.x = element_line(colour="black", size=rel(1.0)),
    axis.ticks.y = element_line(colour="black", size=rel(1.0)),
    legend.position="right"
  )
print(p)
```
