---
title: "MOFA Simulations: infering the true number of latent factors"
output:
  BiocStyle::html_document:
    toc: true
---

```{r}
devtools::load_all("/Users/ricard/mofa/MOFAtools")
library(MOFAtools)
library(data.table)
library(purrr)
library(ggplot2)
```

```{r}
theme_fn <- function() {
    theme(
    # plot.title = element_text(size=titlesize),
    # plot.margin = margin(10,10,10,10),
    axis.title.x=element_text(colour="black",size=rel(1.5), margin=margin(10,0,3,0)),
    axis.title.y=element_text(colour="black",size=rel(1.5), margin=margin(0,10,0,3)),
    axis.text.x=element_text(colour="black",size=rel(1.25)),
    axis.text.y=element_text(colour="black",size=rel(1.25)),
    axis.ticks.x = element_line(colour="black"),
    axis.ticks.y = element_line(colour="black"),
    axis.line.x = element_line(color="black"),
    axis.line.y = element_line(color="black"),
    legend.position="none",
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank()
  )
}
```

<!-- Varying the number of latent variables (K) -->
```{r}

in.folder <- "/Users/ricard/data/MOFA/simulations/18Aug/results/learnK/K"

files <- list.files(in.folder, pattern=".hdf5$")
k_models <- list()
for (i in 1:length(files)) {
  split <- strsplit(files[i],"_")[[1]]
  k <- split[2]
  trial <- substr(split[[3]],1,nchar(split[[3]])-5)
  # k <- as.character(strsplit(files[i],"_")[[1]][2])
  k_models[[paste(k,trial,sep="_")]] <- loadModel(paste0(in.folder,"/",files[i]))
}

k_dt <- data.table(
  infered_k = sapply(k_models, function(x) tail(x@TrainStats$activeK,1) ),
  true_k = as.numeric(sapply(strsplit(names(k_models),"_"),"[[",1)),
  trial = as.numeric(sapply(strsplit(names(k_models),"_"),"[[",2))
) %>% .[true_k<=60]

p <- ggplot(k_dt, aes(x=true_k, y=infered_k, group=true_k)) +
  # geom_point(size=0.5) +
  geom_boxplot(fill="red", alpha=0.5, outlier.shape = NA) +
  geom_abline(slope=1, intercept=0, alpha=0.5) +
  labs(x="Number of true factors", y="Number of infered factors") +
  scale_y_continuous(limits=c(5,61), breaks=c(5,10,15,20,25,30,35,40,45,50,55,60)) +
  scale_x_continuous(limits=c(5,61), breaks=c(5,10,15,20,25,30,35,40,45,50,55,60)) +
  theme_fn()
print(p)

# pdf("/Users/ricard/CLL/simulations/learnK/out/K.pdf", width=7, height=5, useDingbats = F)
# print(p)
# dev.off()
```

<!-- Varying the number of features (D) -->
```{r}

in.folder <- "/Users/ricard/data/MOFA/simulations/18Aug/results/learnK/D"

files <- list.files(in.folder, pattern=".hdf5$")
models <- list()
for (i in 1:length(files)) {
  split <- strsplit(files[i],"_")[[1]]
  d <- split[1]
  trial <- substr(split[[2]],1,nchar(split[[2]])-5)
  models[[paste(d,trial,sep="_")]] <- loadModel(paste0(in.folder,"/",files[i]))
}

dt <- data.table(
  infered_k = sapply(models, function(x) tail(x@TrainStats$activeK,1) ),
  D = as.numeric(sapply(strsplit(names(models),"_"),"[[",1)),
  # D = as.factor(sapply(strsplit(names(models),"_"),"[[",1)),
  trial = as.numeric(sapply(strsplit(names(models),"_"),"[[",2))
) %>% .[,D:=factor(D,levels=sort(unique(D)))] %>%
  .[D %in% c(100,500,1000,2000,3000,4000,5000,6000,7000,8000,9000,10000)]
  # .[D %in% c(1000,2000,3000,4000,5000,6000,7000,8000,9000,10000,15000,20000,25000)]

# ggplot(dt, aes(x=D, y=infered_k, group=D)) +
#   # geom_point(size=0.5) +
#   geom_boxplot(fill="red", alpha=0.5) +
#   # geom_abline(slope=0, intercept=0, alpha=0.5) +
#   labs(x="Number of dimensions", y="Number of infered factors") +
#   scale_y_continuous(limits=c(5,15), breaks=c(5,10,15)) +
#   # scale_x_continuous(limits=c(5,51), breaks=c(5,10,15,20,25,30,35,40,45,50)) +
#   theme_fn()

p <- ggplot(dt, aes(x=D, y=infered_k)) +
  geom_bar(aes(group = trial), position = "dodge", stat="identity", color="white", size=0.3, fill="grey50") +
  geom_hline(yintercept = 10, color="black", size=0.6, linetype="solid") +
  labs(x="Number of features", y="Number of infered factors") +
  scale_y_continuous(limits=c(0,12),breaks=c(5,10)) +
  # scale_x_continuous(limits=c(5,51), breaks=c(5,10,15,20,25,30,35,40,45,50)) +
  theme_fn() +
  theme(
    axis.text.x=element_text(colour="black",size=rel(1.5), angle=90, vjust = 0.5)
  )
print(p)

# pdf("/Users/ricard/CLL/simulations/learnK/out/D.pdf", width = 7, height = 5)
# print(p)
# dev.off()
```

<!-- Varying the number of views (M) -->
```{r}

in.folder <- "/Users/ricard/data/MOFA/simulations/18Aug/results/learnK/M"

files <- list.files(in.folder, pattern=".hdf5$")
models <- list()
for (i in 1:length(files)) {
  split <- strsplit(files[i],"_")[[1]]
  m <- split[1]
  trial <- substr(split[[2]],1,nchar(split[[2]])-5)
  models[[paste(m,trial,sep="_")]] <- loadModel(paste0(in.folder,"/",files[i]))
}

m_dt <- data.table(
  infered_k = sapply(models, function(x) tail(x@TrainStats$activeK,1) ),
  M = as.numeric(sapply(strsplit(names(models),"_"),"[[",1)),
  trial = as.numeric(sapply(strsplit(names(models),"_"),"[[",2))
) %>% .[M<=21] %>% .[,M:=factor(M,levels=sort(unique(M)))]

p <- ggplot(m_dt, aes(x=M, y=infered_k)) +
  geom_bar(aes(group = trial), position = "dodge", stat="identity", color="white", size=0.3, fill="grey50") +
  geom_hline(yintercept = 10, color="black", size=0.6, linetype="solid") +
  labs(x="Number of views", y="Number of infered factors") +
  scale_y_continuous(limits=c(0,12),breaks=c(0,10)) +
  # scale_x_continuous(limits=c(0,14), breaks=c(1,3,5,7,9,11,13)) +
  theme_fn() +
  theme(
    axis.text.x=element_text(colour="black",size=rel(1.5), angle=90, vjust = 0.5, hjust=0.5)
  )
print(p)

# pdf("/Users/ricard/CLL/simulations/learnK/out/M.pdf", width = 7, height = 5)
# print(p)
# dev.off()
```

<!-- Varying the fraction of missing values -->
```{r}

in.folder <- "/Users/ricard/data/MOFA/simulations/18Aug/results/learnK/NA"

files <- list.files(in.folder, pattern=".hdf5$")
models <- list()
for (i in 1:length(files)) {
  split <- strsplit(files[i],"_")[[1]]
  na <- split[1]
  trial <- substr(split[[2]],1,nchar(split[[2]])-5)
  models[[paste(na,trial,sep="_")]] <- loadModel(paste0(in.folder,"/",files[i]))
}

dt <- data.table(
  infered_k = sapply(models, function(x) tail(x@TrainStats$activeK,1) ),
  na = as.numeric(sapply(strsplit(names(models),"_"),"[[",1)),
  trial = as.numeric(sapply(strsplit(names(models),"_"),"[[",2))
) %>% .[,na:=factor(na,levels=sort(unique(na)))] %>%
  .[na %in% c(0.10,0.20,0.30,0.40,0.50,0.60,0.70,0.80,0.90)]

p <- ggplot(dt, aes(x=na, y=infered_k)) +
  geom_bar(aes(group = trial), position = "dodge", stat="identity", color="white", size=0.3, fill="grey50") +
  geom_hline(yintercept = 10, color="black", size=0.6, linetype="solid") +
  labs(x="Fraction of missing values", y="Number of infered factors") +
  scale_y_continuous(limits=c(0,12),breaks=c(5,10)) +
  # scale_x_continuous(limits=c(-0.03,0.93), breaks=c(0,0.05,0.1,0.15,0.2,0.25,0.3,0.35,0.4,0.45,0.5,0.55,0.6,0.65,0.7,0.75,0.8,0.85,0.9)) +
  theme_fn() +
  theme(
    axis.text.x=element_text(colour="black",size=rel(1.5), angle=90, vjust = 0.5, hjust=0.5)
  )
print(p)

pdf("/Users/ricard/CLL/simulations/learnK/out/NA.pdf", width = 8, height = 5)
print(p)
dev.off()
```

