---
title: "MOFA: Assessment of model robustness under downsampling"
output:
  BiocStyle::html_document:
    toc: true
---

```{r}
devtools::load_all("/homes/ricard/mofa/MOFAtools")
# library(MOFAtools)
library(data.table)
library(purrr)
library(ggplot2)
```

```{r}
theme_fn <- function() {
  theme(
    axis.title= element_text(size=rel(1.7)),
    axis.text = element_text(color="black", size=rel(1.3))
    )
}
```

```{r}
out.folder <- "/homes/ricard/MOFA_CLL/robustness/out"
```

<!-- Load trained models -->
```{r}
in.folder <- "/hps/nobackup/stegle/users/ricard/MOFA/CLL/robustness/v2/results"
files <- list.files(in.folder, pattern=".hdf5$")

nsamples_downsampled <- seq(0,100,5)
ntrials <- 25

models <- list()
for (n in as.character(nsamples_downsampled)) {
  models[[n]] <- list()
  for (i in 1:ntrials) {
    if (file.exists(paste0(in.folder,"/",n,"_",i,".hdf5"))) {
        models[[n]][[i]] <- loadModel(paste0(in.folder,"/",n,"_",i,".hdf5"), sortFactors = T)
    }
  }
}
```

<!-- Evidence Lower bound -->
<!-- ```{r} -->
<!-- tmp <- expand.grid(nsamples_downsampled,1:ntrials) %>% as.data.table %>% setnames(c("nsamples_downsampled","trial")) %>% -->
<!--   .[,c("elbo"):=0] -->
<!-- for (n in names(models)) { -->
<!--   for (i in 1:length(models[[n]])) { -->
<!--     tmp[nsamples_downsampled==n & trial==i, elbo:=tail(models[[n]][[i]]@TrainStats$elbo,n=1) ]  -->
<!--   } -->
<!-- } -->
<!-- ggplot(tmp, aes(x=nsamples_downsampled, y=elbo)) + -->
<!--   stat_summary(fun.y="mean", geom="line", size=1) + -->
<!--   stat_summary(fun.data="mean_se", geom="errorbar", width=0.01, alpha=0.6) + -->
<!--   labs(x="Downsampling number", y="Evidence Lower Bound") + -->
<!--   theme_bw() + theme_fn() -->
<!-- ``` -->

<!-- Number of factors -->
```{r}

tmp <- expand.grid(nsamples_downsampled,1:ntrials) %>% as.data.table %>% setnames(c("nsamples_downsampled","trial")) %>%
  .[,c("nfactors"):=0]

for (n in names(models)) {
  for (i in 1:length(models[[n]])) {
    tmp[nsamples_downsampled==n & trial==i, nfactors:=getDimensions(models[[n]][[i]])[["K"]] ] 
  }
}

p <- ggplot(tmp, aes(x=nsamples_downsampled, y=nfactors)) +
  stat_summary(fun.y="mean", geom="line", size=1) +
  stat_summary(fun.data="mean_se", geom="errorbar", width=0.01, alpha=0.6) +
  # scale_y_continuous(limits=c(5,15), breaks=c(8,9,10,11,11,12)) +
  scale_y_continuous(limits=c(5,15), breaks=c(5,7,9,11,13,15)) +
  labs(x="Downsampling number", y="Number of factors") +
  theme_bw() + theme_fn()
# print(p)

pdf(paste0(out.folder,"/nfactors_downsample.pdf"), width = 7.5, height = 5.5)
print(p)
dev.off()
```

<!-- Robustness of factors -->
Plot correlation between factors infered from a downsampled data and factors infered in a complete data set
```{r}

tmp <- expand.grid(nsamples_downsampled,1:ntrials,1:ntrials,as.factor(1:10)) %>% as.data.table %>% setnames(c("nsamples_down","trial_true","trial_down","factor")) %>%
  .[,c("r"):=0]


for (k in unique(tmp$factor)) {
  print(k)
  for (n in names(models)) {
    print(n)
    for (i in 1:length(models[["0"]])) {
      if (length(factorNames(models[["0"]][[i]])) >= as.numeric(k) ) {
        Z_true <- getFactors(models[["0"]][[i]], factors=k, as.data.frame = F)
        for (j in 1:length(models[[n]])) {
          Z_down <- getFactors(models[[n]][[j]], as.data.frame = F)
          tmp[nsamples_down==n & trial_true==i & trial_down==j & factor==k, r:=max(abs(cor(Z_down,Z_true[sampleNames(models[[n]][[j]]),], use="complete.obs")))]
        }
      }
    }
  }
}

saveRDS(tmp, paste0(out.folder,"/corfactors_downsample.rds"))
tmp <- readRDS(paste0(out.folder,"/corfactors_downsample.rds"))

p <- ggplot(tmp, aes(x=nsamples_down, y=r, color=factor, group=factor)) +
  stat_summary(fun.y="mean", geom="line", size=1.25) +
  # stat_summary(fun.data="mean_sd", geom="errorbar", width=0.01, alpha=0.6) +
  # stat_summary(fun.y = mean, fun.ymin = function(x) mean(x) - sd(x), fun.ymax = function(x) mean(x) + sd(x), geom = "errorbar") +
  stat_summary(fun.y = mean, fun.ymin = function(x) mean(x) - 2*sd(x)/ntrials, fun.ymax = function(x) mean(x) + 2*sd(x)/ntrials, geom = "errorbar", width=0.5) +
  scale_y_continuous(limits=c(0,1)) +
  labs(x="Downsampling number", y="Correlation coefficient") +
  theme_bw() + theme_fn() +
  theme(
    legend.position = "right",
    legend.direction='vertical',
    legend.text = element_text(size=rel(1.3)),
    legend.title = element_text(size=rel(1.6))
  )
print(p)


pdf(paste0(out.folder,"/corfactors_downsample.pdf"), width = 7.5, height = 5.5)
print(p)
dev.off()
```

```{r}
stop()
```

<!-- Scatterplots -->

Factor 1 has high correlation even after a significant proportion of downsampling. Find out why
```{r}
# model1 <- models[["0"]][[1]]
# model2 <- models[["50"]][[1]]
# Z_true <- getFactors(model1, factors="1", as.data.frame = T) %>% as.data.table %>% 
#   .[sample%in%sampleNames(model2)] %>% .[,sample:=as.character(sample)] %>% setkey(sample)
# Z_down <- getFactors(model2, factors="1", as.data.frame = T) %>% as.data.table %>% 
#   .[,sample:=as.character(sample)] %>% setkey(sample)
```

